-- ============================================================
-- lastro · A1 — dica de execução traduzida (inglês e espanhol)
-- ============================================================
-- Até aqui a dica só existia em português (`exercicio.dica_execucao`): quem
-- usava o app em inglês ou espanhol via a dica em português (achado A1 da
-- auditoria de linguagem, 2026-09-25). Esta coluna guarda a dica no idioma da
-- pessoa, ao lado do nome já traduzido em `exercicio_traducao`.
--
-- As 436 traduções (218 exercícios x 2 idiomas) foram feitas pelo próprio
-- agente, uma vez, sem chamar IA em produção; a origem da dica original
-- continua em `exercicio.dica_execucao_origem`. O texto é tradução do que já
-- está no banco, nunca conteúdo novo. Sem tradução para um idioma, a tela usa
-- a dica em português (mesmo fallback do nome).
--
-- O casamento com o exercício é pela ordem de `exercicio.id` (n = posição
-- 1..218): a conferência abaixo aborta a migração se o número de linhas
-- atualizadas não for exatamente 436.
-- ============================================================

alter table public.exercicio_traducao
  add column if not exists dica_execucao text;

comment on column public.exercicio_traducao.dica_execucao is
  'Dica de execução no idioma da linha. NULL = usa exercicio.dica_execucao (PT-BR).';

do $$
declare
  v_linhas integer;
begin
  with t(n, idioma, dica) as (
    values
  (1, 'en', 'Torso at about 45°, spine straight and locked. If your lower back rounds to pull, the weight is too heavy.'),
  (1, 'es', 'Torso a unos 45°, columna recta y bloqueada. Si la zona lumbar se redondea al tirar, el peso es demasiado alto.'),
  (2, 'en', 'Hold the plate on your chest and curl your torso up without lifting your lower back off the floor. Holding the plate behind your head strains your neck.'),
  (2, 'es', 'Sostén el disco sobre el pecho y enrolla el tronco sin despegar la zona lumbar del suelo. Sujetar el disco detrás de la cabeza fuerza el cuello.'),
  (3, 'en', 'Only the ball of the foot on the platform, knee almost straight and fixed. Do not let the knee bend to help.'),
  (3, 'es', 'Solo el antepié apoyado en la plataforma, con la rodilla casi extendida y fija. No dejes que la rodilla se doble para ayudar.'),
  (4, 'en', 'Facing away from the pulley, elbows pointing forward, extend the rope overhead. Flaring the elbows out shifts the effort to the shoulder.'),
  (4, 'es', 'De espaldas a la polea, con los codos apuntando al frente, extiende la cuerda por encima de la cabeza. Abrir los codos hacia los lados pasa la fuerza al hombro.'),
  (5, 'en', 'Spread the rope ends apart at the end of the movement. Keep the elbow fixed at your side: if it flares out, the chest joins in.'),
  (5, 'es', 'Separa los extremos de la cuerda al final del movimiento. Codo fijo junto al cuerpo: si se abre, el pecho entra en juego.'),
  (6, 'en', 'Push through your heels and squeeze the glutes at the top. If your hamstrings cramp, bring your feet closer to your hips.'),
  (6, 'es', 'Empuja por el talón y aprieta el glúteo arriba. Si los isquiotibiales se acalambran, acerca los pies a la cadera.'),
  (7, 'en', 'Palms down and forearms supported, lift the back of your hand. The load is much lighter than in a regular wrist curl.'),
  (7, 'es', 'Palmas hacia abajo y antebrazos apoyados, sube el dorso de la mano. La carga es bastante menor que en el curl de muñeca normal.'),
  (8, 'en', 'Support your chest and pull one side at a time without twisting your torso. Let the shoulder blade move forward on the way back to get real range of motion.'),
  (8, 'es', 'Apoya el pecho y tira de un lado a la vez sin girar el tronco. Deja que la escápula avance en la vuelta para ganar recorrido real.'),
  (9, 'en', 'Bar on your back, firm step forward and torso upright. A narrow step, foot right behind foot, costs you balance and locks up the movement.'),
  (9, 'es', 'Barra en la espalda, paso firme hacia adelante y tronco erguido. Un paso estrecho, con un pie justo detrás del otro, quita el equilibrio y traba el movimiento.'),
  (10, 'en', 'Pull the elbow toward the hip on the same side. Twisting your torso to reach more range hides the lack of lat strength.'),
  (10, 'es', 'Lleva el codo hacia la cadera del mismo lado. Girar el tronco para alcanzar más recorrido esconde la falta de fuerza del dorsal.'),
  (11, 'en', 'Palms up, pull the bar to your navel with a stable torso. Shrugging your shoulders as you pull shifts the target to the traps.'),
  (11, 'es', 'Palmas hacia arriba, lleva la barra al ombligo con el tronco estable. Encoger los hombros al tirar cambia el objetivo al trapecio.'),
  (12, 'en', 'Work one side at a time without letting your hips rotate. Compare the sides: a big asymmetry is worth noting.'),
  (12, 'es', 'Trabaja un lado a la vez sin dejar que la cadera rote. Compara los lados: una asimetría grande vale la pena anotarla.'),
  (13, 'en', 'Come up only until your torso is in line with your legs. Going past that line compresses the lower back without working the muscles any harder.'),
  (13, 'es', 'Sube solo hasta que el tronco quede alineado con las piernas. Pasar de esa línea comprime la zona lumbar sin trabajar más los músculos.'),
  (14, 'en', 'Pull the bar to your collarbone with your chest open. Behind the neck is unnecessary and stresses the shoulder.'),
  (14, 'es', 'Lleva la barra hasta la clavícula con el pecho abierto. Detrás de la nuca no es necesario y estresa el hombro.'),
  (15, 'en', 'Adjust the seat until your armpit rests on top of the pad and your elbow lines up with the machine''s axis. Lower slowly until almost straight.'),
  (15, 'es', 'Ajusta el asiento hasta que la axila apoye en la parte superior del cojín y el codo quede alineado con el eje. Baja despacio hasta casi estirar.'),
  (16, 'en', 'Lift the dumbbells close to your body, leading with the elbows. Raising the wrists above the elbows takes the delt out of the movement.'),
  (16, 'es', 'Sube las mancuernas pegadas al cuerpo guiando con los codos. Levantar las muñecas por encima de los codos saca al deltoides del movimiento.'),
  (17, 'en', 'With a wide grip, pull to chest level with your elbows high. Throwing your torso back at the end only makes up for too much weight.'),
  (17, 'es', 'Con el agarre ancho, tira hasta la línea del pecho con los codos altos. Echar el tronco hacia atrás al final solo compensa un exceso de carga.'),
  (18, 'en', 'Adjust the seat until the handles sit at mid-chest level. Keep your shoulders against the backrest throughout the movement.'),
  (18, 'es', 'Ajusta el asiento hasta que las asas queden a la altura de la mitad del pecho. Hombros apoyados en el respaldo durante todo el movimiento.'),
  (19, 'en', 'Feet wide and in front of the bar, lower with your torso upright. Feet too far back take the glutes out and dump the load on the knees.'),
  (19, 'es', 'Pies separados y por delante de la barra, baja con el tronco erguido. Los pies demasiado atrás quitan trabajo al glúteo y cargan la rodilla.'),
  (20, 'en', 'The load sits on your hips, sparing your spine. Lower keeping your torso tall and your whole foot on the floor.'),
  (20, 'es', 'La carga queda en la cadera y protege la columna. Baja manteniendo el tronco alto y el pie entero apoyado en el suelo.'),
  (21, 'en', 'Bring the shoulder toward the opposite knee, not the elbow. Pulling on your neck with your hands strains the neck without working the obliques more.'),
  (21, 'es', 'Lleva el hombro hacia la rodilla contraria, no el codo. Tirar de la nuca con las manos fuerza el cuello sin involucrar más al oblicuo.'),
  (22, 'en', 'Facing the machine, open your arms to shoulder level with your elbows slightly bent. Squeezing the shoulder blades together at the end turns it into a back exercise, not rear delts.'),
  (22, 'es', 'De frente a la máquina, abre los brazos hasta la línea de los hombros con los codos ligeramente flexionados. Juntar las escápulas al final lo convierte en un ejercicio de espalda, no de deltoides posterior.'),
  (23, 'en', 'Hold the plate by its sides and raise it to shoulder height. Going above your head does not work the delt more and pinches the shoulder.'),
  (23, 'es', 'Sostén el disco por los lados y súbelo hasta la altura de los hombros. Subir por encima de la cabeza no trabaja más el deltoides y aprieta el hombro.'),
  (24, 'en', 'Your knee points in the direction of your foot throughout the descent. Your spine keeps the same shape from start to finish, and depth counts as long as that stays true.'),
  (24, 'es', 'La rodilla apunta en la dirección del pie durante toda la bajada. La columna mantiene la misma forma de principio a fin, y la profundidad vale mientras eso se cumpla.'),
  (25, 'en', 'Stack your shoulder over your elbow and lift your hips until your body forms a straight line. Do not let your torso rotate forward.'),
  (25, 'es', 'Coloca el hombro sobre el codo y sube la cadera hasta que el cuerpo forme una línea recta. No dejes que el tronco rote hacia adelante.'),
  (26, 'en', 'The free leg stays bent and still. If your hips drop to the side midway up, the weight is too heavy.'),
  (26, 'es', 'La pierna libre queda flexionada y quieta. Si la cadera cae hacia un lado a mitad de la subida, el peso es demasiado alto.'),
  (27, 'en', 'Line your knee up with the machine''s axis. Go up in control and do not lock the knee hard at the top.'),
  (27, 'es', 'Alinea la rodilla con el eje de la máquina. Sube con control y no bloquees la rodilla con fuerza arriba.'),
  (28, 'en', 'Do not go below ear level if your shoulder complains. Ribs down, without arching your lower back to push.'),
  (28, 'es', 'No bajes de la línea de la oreja si el hombro se queja. Costillas hacia abajo, sin arquear la zona lumbar para empujar.'),
  (29, 'en', 'Balls of the feet on a step, lower your heel below the step and rise to the toes. Quick half-reps at the top leave the calf with almost no stimulus.'),
  (29, 'es', 'Puntas de los pies en un escalón, baja el talón por debajo del escalón y sube hasta la punta. Las medias repeticiones rápidas arriba dejan a la pantorrilla casi sin estímulo.'),
  (30, 'en', 'Adjust the seat so the handles sit below chest level. Press without locking the elbow at the end.'),
  (30, 'es', 'Ajusta el asiento para que las asas queden por debajo de la línea del pecho. Empuja sin bloquear el codo al final.'),
  (31, 'en', 'Lean your torso forward, arms almost straight, and sweep the rope down to your thighs in an arc. Bending the elbows midway swaps lats for triceps.'),
  (31, 'es', 'Inclina el tronco, brazos casi estirados, y lleva la cuerda hasta los muslos en arco. Doblar los codos a mitad de camino cambia dorsal por tríceps.'),
  (32, 'en', 'Rest your elbow on the inside of your thigh and keep it still. Lower until your arm is fully straight.'),
  (32, 'es', 'Apoya el codo en la parte interna del muslo y mantenlo inmóvil. Baja hasta que el brazo quede completamente estirado.'),
  (33, 'en', 'Before raising your legs, tilt your pelvis back and press your lower back down. Without that, the hip flexors take over and the lower back takes the load.'),
  (33, 'es', 'Antes de subir las piernas, gira la pelvis hacia atrás y pega la zona lumbar. Sin eso, el psoas ilíaco asume el trabajo y la zona lumbar recibe la carga.'),
  (34, 'en', 'Palms facing you, elbows close to your torso. The biceps take a bigger part here: expect a heavier load than with the wide grip.'),
  (34, 'es', 'Palmas hacia ti, codos pegados al tronco. El bíceps participa más aquí: espera una carga mayor que con el agarre ancho.'),
  (35, 'en', 'The bar slides close to your legs. The range comes from your hips moving back, not from your spine bending.'),
  (35, 'es', 'La barra se desliza pegada a las piernas. El recorrido viene de la cadera yendo hacia atrás, no de la columna doblándose.'),
  (36, 'en', 'There is tension on the way down too: resist the cable instead of letting it pull you. Keep the elbow fixed at your side.'),
  (36, 'es', 'También hay tensión en la bajada: resiste el cable en lugar de dejar que te jale. Codo fijo junto al cuerpo.'),
  (37, 'en', 'Start with your arms extended and rise until your chin clears the bar. Half-reps at the top leave the lats with almost no stimulus.'),
  (37, 'es', 'Empieza con los brazos extendidos y sube hasta que el mentón pase la barra. Las medias repeticiones arriba dejan al dorsal casi sin estímulo.'),
  (38, 'en', 'Elbow pointing up and tucked in. Lower behind your head with control: letting go at the bottom is where the elbow suffers.'),
  (38, 'es', 'Codo apuntando hacia arriba y cerrado. Baja detrás de la cabeza con control: soltar abajo es donde sufre el codo.'),
  (39, 'en', 'One arm at a time, elbow fixed at your side. Twisting your torso to follow the cable hides the lack of biceps strength.'),
  (39, 'es', 'Un brazo a la vez, codo fijo junto al cuerpo. Girar el tronco para acompañar el cable esconde la falta de fuerza del bíceps.'),
  (40, 'en', 'Facing away from the pulley, raise the cable in front of you to shoulder level. Lowering fast wastes the tension the cable gives at the end of the movement.'),
  (40, 'es', 'De espaldas a la polea, sube el cable al frente hasta la línea de los hombros. Bajar rápido desperdicia la tensión que da el cable al final del movimiento.'),
  (41, 'en', 'Lying on your side, raise the top leg slightly backward, not forward. Bringing the leg forward shifts the work to the hip flexor.'),
  (41, 'es', 'Acostado de lado, sube la pierna de arriba ligeramente hacia atrás, no hacia adelante. Llevar la pierna al frente pasa el trabajo al flexor de la cadera.'),
  (42, 'en', 'Lift only your shoulder blades off the floor; you do not need to sit up. Keep your chin away from your chest, eyes on the ceiling.'),
  (42, 'es', 'Despega solo las escápulas del suelo; no hace falta sentarse. Mantén el mentón lejos del pecho, con la mirada al techo.'),
  (43, 'en', 'Body in a straight line from heels to head. Sagging hips dump load on the lower back; high hips take the chest out of it.'),
  (43, 'es', 'Cuerpo en línea recta, del talón a la cabeza. La cadera caída carga la zona lumbar; la cadera alta saca al pecho del trabajo.'),
  (44, 'en', 'Rise until your torso lines up with your legs and stop: hyperextending recruits nothing more. Slow movement in both phases.'),
  (44, 'es', 'Sube hasta alinear el tronco con las piernas y para: hiperextender no recluta más. Movimiento lento en las dos fases.'),
  (45, 'en', 'Back on the bench and bar on your hips, rise until your torso is parallel to the floor. Arching your lower back at the top looks like more range but it is not glute.'),
  (45, 'es', 'Espalda en el banco y barra en la cadera, sube hasta que el tronco quede paralelo al suelo. Arquear la zona lumbar arriba parece más recorrido, pero no es glúteo.'),
  (46, 'en', 'Overhand grip, wrist firm and in line with your forearm. A lighter load than the regular curl is expected: the brachioradialis does the work here.'),
  (46, 'es', 'Agarre prono, muñeca firme y alineada con el antebrazo. Es normal una carga menor que en el curl directo: aquí trabaja el braquiorradial.'),
  (47, 'en', 'Shoulder blades together and pinned to the bench, feet firm on the floor. The bar comes down to nipple level, not to your neck.'),
  (47, 'es', 'Escápulas juntas y fijas en el banco, pies firmes en el suelo. La barra baja a la línea del pezón, no al cuello.'),
  (48, 'en', 'Raise your shoulders toward your ears, straight up. Rolling the shoulders in circles does not work the traps more and irritates the joint.'),
  (48, 'es', 'Sube los hombros hacia las orejas, en línea recta. Rotar los hombros en círculo no trabaja más el trapecio e irrita la articulación.'),
  (49, 'en', 'From a high plank, bring your knees to your chest alternately, hips in line with your shoulders. Lifting the hips makes it easier and takes the abs out of the work.'),
  (49, 'es', 'Desde una plancha alta, lleva las rodillas al pecho alternando, con la cadera en línea con los hombros. Subir la cadera lo facilita y saca al abdomen del trabajo.'),
  (50, 'en', 'Choose the assistance that makes the last reps hard. Letting the platform push you at the start takes the work off the weakest part.'),
  (50, 'es', 'Elige la asistencia que haga difíciles las últimas repeticiones. Dejar que la plataforma te empuje al inicio quita el trabajo justo de la parte más débil.'),
  (51, 'en', 'A hip movement, not a spine one: push your hips back with your back locked. Keep the load light: the mechanics are demanding.'),
  (51, 'es', 'Es un movimiento de cadera, no de columna: empuja la cadera hacia atrás con la espalda bloqueada. Carga ligera: la mecánica es exigente.'),
  (52, 'en', 'Ankle cuff on the inner foot, bring the leg in front of the other. Swinging the leg for momentum takes the tension off the adductor.'),
  (52, 'es', 'Tobillera en el pie interno, lleva la pierna por delante de la otra. Balancear la pierna para tomar impulso quita la tensión al aductor.'),
  (53, 'en', 'Place the front foot ahead of the bar so you go straight down. With a fixed track, a badly placed foot forces the knee well past the toes.'),
  (53, 'es', 'Coloca el pie delantero adelante de la barra para bajar recto. Con el riel fijo, un pie mal colocado obliga a la rodilla a pasar mucho de la punta del pie.'),
  (54, 'en', 'Start by pulling your shoulder blades down, before bending your elbows. Rise bringing your chest to the bar, not your chin.'),
  (54, 'es', 'Empieza bajando las escápulas, antes de doblar los codos. Sube llevando el pecho a la barra, no el mentón.'),
  (55, 'en', 'Elbow slightly bent and constant. The movement is bringing your hands together in front of your chest, not pushing.'),
  (55, 'es', 'Codo ligeramente flexionado y constante. El movimiento es juntar las manos frente al pecho, no empujar.'),
  (56, 'en', 'Ankle cuff on the outer foot, take the leg out to the side with your torso straight. Leaning your body to the opposite side steals range from the glute.'),
  (56, 'es', 'Tobillera en el pie externo, lleva la pierna hacia el lado con el tronco recto. Inclinar el cuerpo hacia el lado contrario le quita recorrido al glúteo.'),
  (57, 'en', 'Keep your torso steady and upright; swinging back becomes momentum, not strength. Pull to your abdomen, squeezing the shoulder blades together.'),
  (57, 'es', 'Tronco estable en vertical; balancearse hacia atrás se vuelve impulso, no fuerza. Tira hasta el abdomen, juntando las escápulas.'),
  (58, 'en', 'Elbow still at your side; only the forearm moves. Swinging your torso to lift shifts the work to the lower back.'),
  (58, 'es', 'Codo quieto junto al cuerpo; solo se mueve el antebrazo. Balancear el tronco para subir pasa el trabajo a la zona lumbar.'),
  (59, 'en', 'Whole foot on the platform, knee following the line of the foot. Push without extending the knee to lockout.'),
  (59, 'es', 'Pie entero en la plataforma, rodilla siguiendo la línea del pie. Empuja sin extender la rodilla hasta el bloqueo.'),
  (60, 'en', 'Whole back against the backrest. Press without letting the shoulder roll forward at the end of the movement.'),
  (60, 'es', 'Toda la espalda apoyada en el respaldo. Empuja sin proyectar el hombro hacia adelante al final del movimiento.'),
  (61, 'en', 'With palms up, pull the bar to your navel with your torso near 45 degrees. Straightening up on every rep uses the lower back as a lever.'),
  (61, 'es', 'Con las palmas hacia arriba, lleva la barra al ombligo con el tronco cerca de 45 grados. Enderezarse en cada repetición usa la zona lumbar como palanca.'),
  (62, 'en', 'Elbow tucked against your body at 90 degrees, rotate your forearm outward. Moving the elbow away from your torso takes the work off the rotator cuff.'),
  (62, 'es', 'Codo pegado al cuerpo a 90 grados, gira el antebrazo hacia afuera. Separar el codo del tronco quita el trabajo al manguito rotador.'),
  (63, 'en', 'The bar rises close to your shins and your spine does not change shape. If your lower back rounds at the start, reduce the load and recheck your hip position.'),
  (63, 'es', 'La barra sube pegada a la espinilla y la columna no cambia de forma. Si la zona lumbar se redondea al inicio, reduce la carga y revisa la posición de la cadera.'),
  (64, 'en', 'Hands together forming a diamond under your chest, elbows close to your body. If your wrist hurts, move your hands slightly apart.'),
  (64, 'es', 'Manos juntas formando un rombo bajo el pecho, codos pegados al cuerpo. Si te duele la muñeca, separa un poco las manos.'),
  (65, 'en', 'Elbow tucked against your torso on the way up. If the shoulder comes forward to help, the weight is too heavy.'),
  (65, 'es', 'Codo pegado al tronco durante la subida. Si el hombro se adelanta para ayudar, el peso es demasiado alto.'),
  (66, 'en', 'Raise the bar to eye level with your arms almost straight. Swinging your torso for momentum shifts the work to the lower back.'),
  (66, 'es', 'Sube la barra hasta la línea de los ojos con los brazos casi estirados. Balancear el tronco para tomar impulso pasa el trabajo a la zona lumbar.'),
  (67, 'en', 'Lower the bar toward your forehead by bending only the elbow. Moving the arm along with it on the way down turns it into a pullover and takes load off the triceps.'),
  (67, 'es', 'Baja la barra hacia la frente doblando solo el codo. Mover el brazo junto con ella en la bajada lo convierte en pullover y quita carga al tríceps.'),
  (68, 'en', 'Lower straight down, with your back knee almost touching the floor. Your front knee points in the direction of your foot.'),
  (68, 'es', 'Baja en vertical, con la rodilla de atrás casi tocando el suelo. La rodilla delantera apunta en la dirección del pie.'),
  (69, 'en', 'Back against the support and feet in the middle of the platform, lower to the end of the range. Lifting your hips off the pad at the bottom shifts the load to the lower back.'),
  (69, 'es', 'Espalda pegada al apoyo y pies en el centro de la plataforma, baja hasta el final del recorrido. Despegar la cadera del respaldo abajo pasa la carga a la zona lumbar.'),
  (70, 'en', 'Lying with your head toward the pulley, extend the bar over your chest. The cable keeps tension at the top; do not rest with locked arms.'),
  (70, 'es', 'Acostado con la cabeza hacia la polea, extiende la barra sobre el pecho. El cable mantiene la tensión arriba; no descanses con los brazos bloqueados.'),
  (71, 'en', 'Finish with hips, knees and shoulders in line and the glutes squeezed. Going past that arches the lower back instead of working the glutes.'),
  (71, 'es', 'Termina con cadera, rodilla y hombro alineados y el glúteo apretado. Pasar de eso arquea la zona lumbar en lugar de trabajar el glúteo.'),
  (72, 'en', 'Press one dumbbell at a time without leaning your torso to the side. The abs keep your body straight; the shoulder only pushes.'),
  (72, 'es', 'Empuja una mancuerna a la vez sin inclinar el tronco hacia un lado. El abdomen mantiene el cuerpo recto; el hombro solo empuja.'),
  (73, 'en', 'Dumbbell in one hand, lean your torso toward that side and come back. Holding a dumbbell in both hands cancels the exercise: one side balances the other.'),
  (73, 'es', 'Mancuerna en una mano, inclina el tronco hacia ese lado y vuelve. Sujetar una mancuerna en cada mano anula el ejercicio: un lado equilibra al otro.'),
  (74, 'en', 'Spine parallel to the floor and hips fixed. Pull the elbow close to your body; if your torso rotates to follow, reduce the load.'),
  (74, 'es', 'Columna paralela al suelo y cadera fija. Tira del codo pegado al cuerpo; si el tronco rota para acompañar, reduce la carga.'),
  (75, 'en', 'Crossed cables, open your arms at shoulder height. Letting the elbows drop below that line turns the movement into a row.'),
  (75, 'es', 'Cables cruzados, abre los brazos a la altura de los hombros. Dejar que los codos caigan por debajo de esa línea convierte el movimiento en remo.'),
  (76, 'en', 'Adjust the seat until your elbow lines up with the axis. Return slowly instead of letting the weight pull you.'),
  (76, 'es', 'Ajusta el asiento hasta que el codo quede alineado con el eje. Vuelve despacio en lugar de dejar que el peso te jale.'),
  (77, 'en', 'Hips square on the seat, without rotating toward the pushing side. Compare the sides every set.'),
  (77, 'es', 'Cadera cuadrada en el asiento, sin rotar hacia el lado que empuja. Compara los lados en cada serie.'),
  (78, 'en', 'Hips square to the front throughout the movement. Going higher by rotating the pelvis swaps glute for lower back.'),
  (78, 'es', 'Cadera cuadrada hacia el frente durante todo el movimiento. Subir más rotando la pelvis cambia glúteo por zona lumbar.'),
  (79, 'en', 'Lock your legs in well and lower the bar to the lower part of your chest. Shortening the descent to handle more weight takes the chest out of the work.'),
  (79, 'es', 'Fija bien las piernas y baja la barra hasta la parte baja del pecho. Acortar la bajada para aguantar más carga saca al pecho del trabajo.'),
  (80, 'en', 'Seated with back support, lower the bar behind your head using only the elbow. Arching your lower back to lift shows too much weight.'),
  (80, 'es', 'Sentado con apoyo en la espalda, baja la barra detrás de la cabeza solo con el codo. Arquear la zona lumbar para subir indica demasiada carga.'),
  (81, 'en', 'Elbows tucked against your body, extend until your arms lock out. Letting the elbows rise on the way back turns the pushdown into a pulldown.'),
  (81, 'es', 'Codos pegados al cuerpo, extiende hasta bloquear el brazo. Dejar que los codos suban en la vuelta convierte el jalón de tríceps en un jalón dorsal.'),
  (82, 'en', 'Hips resting on the pad, without lifting off. Curl up to the comfortable limit and lower resisting.'),
  (82, 'es', 'Cadera apoyada en el cojín, sin despegarla. Sube hasta el límite cómodo y baja resistiendo.'),
  (83, 'en', 'Balancing on one leg, lean your torso forward while the other leg rises behind you. Opening the hip to the side costs balance and takes the work off the hamstring.'),
  (83, 'es', 'Apoyado en una pierna, inclina el tronco mientras la otra pierna sube atrás. Abrir la cadera hacia el lado quita el equilibrio y el trabajo al isquiotibial.'),
  (84, 'en', 'Arm parallel to the floor and elbow still. Extend until your arm is straight and hold for a moment.'),
  (84, 'es', 'Brazo paralelo al suelo y codo quieto. Extiende hasta que el brazo quede recto y sostén un instante.'),
  (85, 'en', 'Back foot supported, weight on the front leg. Too short a distance pushes the knee forward; adjust until the descent feels comfortable.'),
  (85, 'es', 'Pie de atrás apoyado, peso en la pierna delantera. Una distancia demasiado corta manda la rodilla hacia adelante; ajusta hasta que la bajada sea cómoda.'),
  (86, 'en', 'Rest your whole arm on the pad with your armpit against it. The lowering phase is the part that usually hurts when done loosely: control it all the way.'),
  (86, 'es', 'Apoya todo el brazo en el banco, con la axila pegada. La bajada es la parte que suele lastimar cuando se hace suelta: contrólala hasta el final.'),
  (87, 'en', 'One leg at a time, extend until almost locked and lower slowly. Gripping the seat hard to lift your hips makes up for too much weight.'),
  (87, 'es', 'Una pierna a la vez, extiende hasta casi bloquear y baja despacio. Agarrarse fuerte del asiento para subir la cadera compensa un exceso de carga.'),
  (88, 'en', 'Ankles anchored, lower your torso forward as slowly as you can. Bending at the hips on the way down takes the hamstrings out of the work.'),
  (88, 'es', 'Tobillos fijos, baja el tronco hacia adelante lo más despacio que puedas. Doblar la cadera en la bajada saca a los isquiotibiales del trabajo.'),
  (89, 'en', 'Lock your feet in well before starting. The bar comes down to the lower line of your chest.'),
  (89, 'es', 'Fija bien los pies antes de empezar. La barra baja a la línea inferior del pecho.'),
  (90, 'en', 'Thumbs up, raise the rope without moving your elbows away from your body. Pulling with the shoulder at the end shortens the brachialis work.'),
  (90, 'es', 'Pulgares hacia arriba, sube la cuerda sin separar los codos del cuerpo. Tirar con el hombro al final acorta el trabajo del braquial.'),
  (91, 'en', 'Pull the bar close to your body to chest height, elbows above the wrists. Going up to the chin pinches the shoulder with no gain.'),
  (91, 'es', 'Lleva la barra pegada al cuerpo hasta la altura del pecho, con los codos por encima de las muñecas. Subir hasta el mentón aprieta el hombro sin beneficio.'),
  (92, 'en', 'Just up and down: do not roll your shoulders. Hold for a moment at the top instead of adding load.'),
  (92, 'es', 'Solo sube y baja: no rotes los hombros. Sostén un instante arriba en lugar de aumentar la carga.'),
  (93, 'en', 'One wrist at a time, forearm supported, move only your hand up and down. Letting the dumbbell roll to your fingertips is optional, but do it slowly.'),
  (93, 'es', 'Una muñeca a la vez, antebrazo apoyado, sube y baja solo la mano. Dejar rodar la mancuerna hasta la punta de los dedos es opcional, pero hazlo despacio.'),
  (94, 'en', 'With the pulleys low, raise your arms in an arc to chest height. Bending the elbows along the way turns it into a front raise.'),
  (94, 'es', 'Con las poleas abajo, sube los brazos en arco hasta la altura del pecho. Doblar los codos en el camino lo convierte en elevación frontal.'),
  (95, 'en', 'Step up by pushing through the heel of the top leg, without pushing off the bottom leg. Use a box that leaves your knee at a comfortable angle.'),
  (95, 'es', 'Sube empujando por el talón de la pierna de arriba, sin impulso de la pierna de abajo. Usa un cajón que deje la rodilla en un ángulo cómodo.'),
  (96, 'en', 'Feet wide and turned out, knees following your feet. Knees caving in on the way up overload the joint.'),
  (96, 'es', 'Pies bien separados y girados hacia afuera, rodillas siguiendo los pies. Las rodillas cerrándose hacia adentro en la subida sobrecargan la articulación.'),
  (97, 'en', 'Pull the handle to your upper chest, driving your elbows down and back. Leaning your torso back on every rep turns the pulldown into a row.'),
  (97, 'es', 'Lleva el agarre hasta la parte alta del pecho bajando los codos hacia abajo y atrás. Inclinar el tronco hacia atrás en cada repetición convierte el jalón en un remo.'),
  (98, 'en', 'Heavy dumbbells in your hands, walk in short steps with shoulders back and torso upright. Letting the shoulders drop forward shifts the load to the lower back.'),
  (98, 'es', 'Mancuernas pesadas en las manos, camina con pasos cortos, hombros atrás y tronco erguido. Dejar caer los hombros hacia adelante pasa la carga a la zona lumbar.'),
  (99, 'en', 'Adjust the backrest so the machine''s axis is at navel height. The movement is shortening the distance between sternum and hips, not pushing with your arms.'),
  (99, 'es', 'Ajusta el respaldo para que el eje de la máquina quede a la altura del ombligo. El movimiento es acortar la distancia entre esternón y cadera, no empujar con los brazos.'),
  (100, 'en', 'Abs tight and glutes squeezed so your lower back does not become a hinge. The bar passes close to your face, not in front of your body.'),
  (100, 'es', 'Abdomen firme y glúteo contraído para que la zona lumbar no se convierta en bisagra. La barra pasa pegada a la cara, no delante del cuerpo.'),
  (101, 'en', 'Step back and lower until your back knee almost touches the floor. The weight stays on the heel of the front leg, not on the ball of the foot.'),
  (101, 'es', 'Da el paso hacia atrás y baja hasta que la rodilla de atrás casi toque el suelo. El peso queda en el talón de la pierna delantera, no en la punta del pie.'),
  (102, 'en', 'Forearms supported on your thigh or the bench, palms up, lift only the wrist. Lifting the forearm off the support turns the exercise into a curl.'),
  (102, 'es', 'Antebrazos apoyados en el muslo o en el banco, palmas hacia arriba, sube solo la muñeca. Levantar el antebrazo del apoyo convierte el ejercicio en curl.'),
  (103, 'en', 'Forearms supported and back against the pad, bring your knees to your chest by curling the pelvis. Swinging your legs to get up spends momentum, not abs.'),
  (103, 'es', 'Antebrazos apoyados y espalda en el respaldo, lleva las rodillas al pecho enrollando la pelvis. Balancear las piernas para subir gasta impulso, no abdomen.'),
  (104, 'en', 'Whole arm supported on the pad, lower until almost extended. Dropping the dumbbell at the end of the descent is when the biceps gets hurt most.'),
  (104, 'es', 'Todo el brazo apoyado en el banco, baja hasta casi extender. Soltar la mancuerna al final de la bajada es cuando más se lastima el bíceps.'),
  (105, 'en', 'Lying down, extend the opposite arm and leg slowly while keeping your lower back pressed to the floor. If it lifts off, shorten the range.'),
  (105, 'es', 'Acostado, extiende brazo y pierna contrarios despacio manteniendo la zona lumbar pegada al suelo. Si se despega, acorta el recorrido.'),
  (106, 'en', 'Lying down, alternate your straight legs close to the floor. If your lower back lifts off, raise your legs higher.'),
  (106, 'es', 'Acostado, alterna las piernas estiradas cerca del suelo. Si la zona lumbar se despega, sube más las piernas.'),
  (107, 'en', 'Torso steady and supported. Only the knee bends: the hips stay still.'),
  (107, 'es', 'Tronco estable y apoyado. Solo se dobla la rodilla: la cadera queda quieta.'),
  (108, 'en', 'Grip slightly wider than shoulder width; wider than that shortens the range with no gain. The shoulder blades go down first.'),
  (108, 'es', 'Agarre un poco más ancho que los hombros; más abierto que eso acorta el recorrido sin beneficio. Las escápulas bajan primero.'),
  (109, 'en', 'Dumbbells at your sides, lower keeping your chest open. Letting the shoulders roll forward rounds the back.'),
  (109, 'es', 'Mancuernas a los lados del cuerpo, baja manteniendo el pecho abierto. Dejar que los hombros rueden hacia adelante redondea la espalda.'),
  (110, 'en', 'Feet elevated on the bench, lower your chest close to the floor with your body straight. Letting the hips rise takes load off the chest.'),
  (110, 'es', 'Pies elevados en el banco, baja el pecho cerca del suelo con el cuerpo recto. Dejar que la cadera suba quita carga al pecho.'),
  (111, 'en', 'Your chest does not come off the pad. The support exists precisely to take the lower back out of it: letting your torso rise defeats the purpose of the machine.'),
  (111, 'es', 'El pecho no se despega del cojín. El apoyo existe justamente para sacar la zona lumbar del trabajo: dejar subir el tronco anula el motivo de la máquina.'),
  (112, 'en', 'With support for your hands, take your knees forward and your torso back in a straight line. Bending at the hips turns the sissy squat into a regular squat.'),
  (112, 'es', 'Con apoyo para las manos, lleva las rodillas al frente y el tronco hacia atrás en una línea recta. Doblar la cadera convierte la sentadilla sissy en una sentadilla común.'),
  (113, 'en', 'One arm at a time, thumb up throughout. Swinging your body to lift the dumbbell shows too much weight.'),
  (113, 'es', 'Un brazo a la vez, pulgar hacia arriba todo el tiempo. Balancear el cuerpo para subir la mancuerna indica demasiada carga.'),
  (114, 'en', 'Knees slightly bent, push your hips back until you feel the hamstrings stretch. Going lower by rounding your back does not work the hamstrings more.'),
  (114, 'es', 'Rodillas ligeramente flexionadas, empuja la cadera hacia atrás hasta sentir el estiramiento de los isquiotibiales. Bajar más redondeando la espalda no trabaja más los isquiotibiales.'),
  (115, 'en', 'Adjust the seat until the handles are at chest level. Bring them together with your chest, keeping your shoulders against the backrest.'),
  (115, 'es', 'Ajusta el asiento hasta que las asas queden a la altura del pecho. Júntalas con el pecho, manteniendo los hombros apoyados en el respaldo.'),
  (116, 'en', 'Pull one arm at a time, keeping your chest facing the pulley. Rotating the shoulder back steals range from the lats.'),
  (116, 'es', 'Tira de un brazo a la vez manteniendo el pecho de frente a la polea. Rotar el hombro hacia atrás le quita recorrido al dorsal.'),
  (117, 'en', 'Press the end of the bar up and forward, along the arc it asks for. Arching your lower back to finish the movement hides a lack of shoulder strength.'),
  (117, 'es', 'Empuja el extremo de la barra hacia arriba y adelante, en el arco que pide. Arquear la zona lumbar para terminar el movimiento esconde falta de fuerza en el hombro.'),
  (118, 'en', 'Back foot on the bench and front foot ahead of the bar, lower straight down the track. Push through the front heel; the back leg only balances.'),
  (118, 'es', 'Pie de atrás en el banco y pie delantero adelante de la barra, baja recto por el riel. Empuja por el talón delantero; la pierna de atrás solo equilibra.'),
  (119, 'en', 'Hips back, neutral spine, chest out. The bar touches your abdomen and comes down in control.'),
  (119, 'es', 'Cadera hacia atrás, columna neutra, pecho hacia afuera. La barra toca el abdomen y baja controlada.'),
  (120, 'en', 'Bench between 30 and 45 degrees and the bar coming down to your upper chest. Lifting your hips off the bench cancels the incline.'),
  (120, 'es', 'Banco entre 30 y 45 grados y la barra bajando a la parte alta del pecho. Despegar la cadera del banco anula la inclinación.'),
  (121, 'en', 'Adjust the seat until the handles are at shoulder height. Press without locking the elbow at the end.'),
  (121, 'es', 'Ajusta el asiento hasta que las asas queden a la altura de los hombros. Empuja sin bloquear el codo al final.'),
  (122, 'en', 'Palms facing each other, lower the dumbbells beside your head. Elbows flaring out relieve the triceps and strain the elbow.'),
  (122, 'es', 'Palmas enfrentadas, baja las mancuernas junto a la cabeza. Los codos abriéndose hacia afuera alivian el tríceps y fuerzan el codo.'),
  (123, 'en', 'Take the back leg crossing behind the front one and lower. The front knee follows the direction of the toes; letting it cave inward is the common mistake.'),
  (123, 'es', 'Lleva la pierna de atrás cruzando por detrás de la delantera y baja. La rodilla delantera sigue la punta del pie; dejarla caer hacia adentro es el error común.'),
  (124, 'en', 'Open your arms in an arc until you feel your chest stretch, elbows slightly bent. Going below the bench line stresses the shoulder.'),
  (124, 'es', 'Abre los brazos en arco hasta sentir el estiramiento del pecho, con los codos ligeramente flexionados. Bajar de la línea del banco estresa el hombro.'),
  (125, 'en', 'Hold onto a support and lean your body away from the dumbbell. Raising past shoulder line shifts the load to the traps.'),
  (125, 'es', 'Agárrate de un apoyo e inclina el cuerpo hacia el lado contrario a la mancuerna. Subir más allá de la línea del hombro pasa la carga al trapecio.'),
  (126, 'en', 'Position your body so the bar rises to the lower part of your chest. Since the track is fixed, standing too far from the bar forces you to pull with your arms.'),
  (126, 'es', 'Coloca el cuerpo para que la barra suba hasta la parte baja del pecho. Como el riel es fijo, estar demasiado lejos de la barra obliga a tirar con los brazos.'),
  (127, 'en', 'Chest on the pad, shoulder relaxed at the start. Pull with your elbows, not your hands.'),
  (127, 'es', 'Pecho en el apoyo, hombro relajado al inicio. Tira con los codos, no con las manos.'),
  (128, 'en', 'Line your knee up with the machine''s axis. Hips glued to the seat; if they rise to help, reduce the load.'),
  (128, 'es', 'Alinea la rodilla con el eje de la máquina. Cadera pegada al asiento; si sube para ayudar, reduce la carga.'),
  (129, 'en', 'Back against the wall and knees at 90 degrees, weight on your heels. Resting your hands on your thighs relieves exactly the quads the exercise wants to tire.'),
  (129, 'es', 'Espalda contra la pared y rodillas a 90 grados, con el peso en los talones. Apoyar las manos en los muslos alivia justo el cuádriceps que el ejercicio quiere cansar.'),
  (130, 'en', 'Elbows still at your sides, raise the bar until your biceps contract. Swinging your torso to lift shifts the load to your back.'),
  (130, 'es', 'Codos quietos junto al cuerpo, sube la barra hasta que el bíceps se contraiga. Balancear el tronco para subir pasa la carga a la espalda.'),
  (131, 'en', 'With the bar on the track, raise your shoulders and hold for a moment at the top. Bending your elbows to pull turns it into an upright row.'),
  (131, 'es', 'Con la barra en el riel, sube los hombros y sostén un instante arriba. Doblar los codos para tirar lo convierte en remo al mentón.'),
  (132, 'en', 'The shoulder rises toward the ear, with your neck relaxed. Pushing your chin forward is not part of the movement.'),
  (132, 'es', 'El hombro sube hacia la oreja, con el cuello relajado. Empujar el mentón hacia adelante no es parte del movimiento.'),
  (133, 'en', 'Elbow pointing at the ceiling and still. The bar comes down to your forehead or slightly behind, always in control.'),
  (133, 'es', 'Codo apuntando al techo y quieto. La barra baja hasta la frente o un poco más atrás, siempre controlada.'),
  (134, 'en', 'Let the machine guide the arc, without forcing a path of your own. Adjust the seat until your arms start straight above your head.'),
  (134, 'es', 'Deja que el equipo guíe el arco, sin forzar una trayectoria propia. Ajusta el asiento hasta que los brazos empiecen estirados por encima de la cabeza.'),
  (135, 'en', 'Hold the dumbbell against your chest and lower with your torso upright, knees following your toes. Letting the dumbbell drift away from your body pulls your torso forward.'),
  (135, 'es', 'Sostén la mancuerna junto al pecho y baja con el tronco erguido, rodillas siguiendo la punta de los pies. Dejar que la mancuerna se aleje del cuerpo tira el tronco hacia adelante.'),
  (136, 'en', 'Anchor your hips: they stay still and only the torso curls. Pulling with your arms turns the exercise into a row.'),
  (136, 'es', 'Fija la cadera: queda quieta y solo el tronco se enrolla. Tirar con los brazos convierte el ejercicio en un remo.'),
  (137, 'en', 'Stand in the center of the bar and push the floor away with your legs. Raising your hips before your shoulders turns the lift into a stiff-leg deadlift.'),
  (137, 'es', 'Párate en el centro de la barra y empuja el suelo con las piernas. Subir la cadera antes que los hombros convierte el levantamiento en peso muerto rumano.'),
  (138, 'en', 'Chest supported, arms hanging straight down. The body does not move: if your torso rises along with it, reduce the load.'),
  (138, 'es', 'Pecho apoyado, brazos colgando en vertical. El cuerpo no se mueve: si el tronco sube junto, reduce la carga.'),
  (139, 'en', 'Lower the bar only to the back of your neck, without pushing your head forward. Only do it if your shoulder has the mobility for it without pain.'),
  (139, 'es', 'Baja la barra solo hasta la nuca, sin empujar la cabeza hacia adelante. Hazlo solo si el hombro tiene movilidad para eso sin dolor.'),
  (140, 'en', 'Bar resting in front of your shoulders, elbows high, lower with your torso upright. Elbows dropping let the bar slide toward your wrists.'),
  (140, 'es', 'Barra apoyada al frente de los hombros, codos altos, baja con el tronco erguido. Los codos cayendo dejan que la barra resbale hacia las muñecas.'),
  (141, 'en', 'Knees almost straight, lower the dumbbells close to your legs by taking your hips back. Rounding your spine to go lower overloads the lower back.'),
  (141, 'es', 'Rodillas casi estiradas, baja las mancuernas pegadas a las piernas llevando la cadera hacia atrás. Redondear la columna para bajar más sobrecarga la zona lumbar.'),
  (142, 'en', 'On all fours, raise your leg until your thigh lines up with your torso. Arching your lower back to go higher takes the glute out of the movement.'),
  (142, 'es', 'En cuatro apoyos, sube la pierna hasta que el muslo quede alineado con el tronco. Arquear la zona lumbar para subir más saca al glúteo del movimiento.'),
  (143, 'en', 'Feet locked on the decline bench, curl your torso up one vertebra at a time. Pulling your head with your hands strains the neck.'),
  (143, 'es', 'Pies fijos en el banco declinado, enrolla el tronco vértebra por vértebra. Tirar de la cabeza con las manos fuerza el cuello.'),
  (144, 'en', 'Arms locked: the torso rotates, not the shoulders. Feet firm and hips steady throughout the whole arc.'),
  (144, 'es', 'Brazos bloqueados: quien gira es el tronco, no los hombros. Pies firmes y cadera estable durante todo el arco.'),
  (145, 'en', 'Raise to shoulder height and stop. Swinging your torso to throw the weight is the most common mistake here.'),
  (145, 'es', 'Sube hasta la altura de los hombros y para. Balancear el tronco para lanzar el peso es el error más común aquí.'),
  (146, 'en', 'Hanging from the bar, raise your legs by curling the pelvis, without swinging. Raising only the legs without curling the pelvis works the hip flexor more.'),
  (146, 'es', 'Colgado de la barra, sube las piernas enrollando la pelvis, sin balancearte. Subir solo las piernas sin enrollar la pelvis trabaja más el flexor de la cadera.'),
  (147, 'en', 'The movement comes from your hip, not your lower back. Hold onto something firm so your torso does not compensate.'),
  (147, 'es', 'El movimiento viene de la cadera, no de la zona lumbar. Agárrate de algo firme para que el tronco no compense.'),
  (148, 'en', 'Raise your arm out to the side to shoulder height, elbow slightly bent. Leaning your torso away from the pulley steals the hard part of the movement.'),
  (148, 'es', 'Sube el brazo por el lado hasta la altura del hombro, con el codo ligeramente flexionado. Inclinar el tronco lejos de la polea le quita la parte difícil al movimiento.'),
  (149, 'en', 'With palms facing each other, bring the handles down to chin level. Shrugging your shoulders at the end takes the work off the lats and puts it on the traps.'),
  (149, 'es', 'Con las palmas enfrentadas, baja los agarres hasta la línea del mentón. Encoger los hombros al final quita el trabajo al dorsal y lo pasa al trapecio.'),
  (150, 'en', 'In a half squat, take side steps without letting your feet come together. Standing too tall takes the tension off the gluteus medius.'),
  (150, 'es', 'En semisentadilla, da pasos laterales sin dejar que los pies se junten. Estar demasiado erguido quita la tensión al glúteo medio.'),
  (151, 'en', 'Arms extended in front of you, wind the rope until the load rises and unwind slowly. Lowering your arms during the set takes the work off the forearm.'),
  (151, 'es', 'Brazos extendidos al frente, enrolla la cuerda hasta que suba la carga y desenrolla despacio. Bajar los brazos durante la serie quita el trabajo al antebrazo.'),
  (152, 'en', 'Elbow high so the bar does not roll. Your torso stays more vertical than in the back squat: if it falls forward, the weight goes with it.'),
  (152, 'es', 'Codo alto para que la barra no ruede. El tronco queda más vertical que en la sentadilla libre: si cae hacia adelante, el peso se va con él.'),
  (153, 'en', 'Neutral wrist, thumb up, from start to finish. Rotating your hand at the top takes the tension off the brachialis.'),
  (153, 'es', 'Muñeca neutra, pulgar hacia arriba, de principio a fin. Girar la mano arriba quita la tensión al braquial.'),
  (154, 'en', 'Keep your body close to the bench. Going too low with the shoulder rolled forward is what usually hurts here.'),
  (154, 'es', 'Mantén el cuerpo pegado al banco. Bajar demasiado con el hombro rotado hacia adelante es lo que suele lastimar aquí.'),
  (155, 'en', 'Adjust the bench so the bar comes down at nipple level. With a fixed track, a badly positioned bench sends the bar to your neck or your belly.'),
  (155, 'es', 'Ajusta el banco para que la barra baje a la línea de los pezones. Con el riel fijo, un banco mal colocado manda la barra al cuello o al abdomen.'),
  (156, 'en', 'Chin to chest, eyes forward. Rise until your torso is parallel to the floor and hold for a moment at the top.'),
  (156, 'es', 'Mentón al pecho, mirada al frente. Sube hasta que el tronco quede paralelo al suelo y sostén un instante arriba.'),
  (157, 'en', 'Wrist in line with your forearm, without bending back. Lower to chest level and press up without clanking the dumbbells together.'),
  (157, 'es', 'Muñeca alineada con el antebrazo, sin quebrarla hacia atrás. Baja hasta la línea del pecho y sube sin chocar las mancuernas.'),
  (158, 'en', 'Hands on the bench, lower until your chest touches it. It is the push-up progression: the higher the support, the easier.'),
  (158, 'es', 'Manos en el banco, baja hasta que el pecho lo toque. Es la progresión de la flexión: cuanto más alto el apoyo, más fácil.'),
  (159, 'en', 'Rotate from the ribs, with your hips fixed on the seat. A short, controlled range is worth more than maximum rotation.'),
  (159, 'es', 'Gira desde las costillas, con la cadera fija en el asiento. Un recorrido corto y controlado vale más que el giro máximo.'),
  (160, 'en', 'Torso leaning back, rotate your shoulders from side to side, not just your arms. Moving only the hands leaves the obliques idle.'),
  (160, 'es', 'Tronco inclinado hacia atrás, gira los hombros de un lado al otro, no solo los brazos. Mover solo las manos deja quieto al oblicuo.'),
  (161, 'en', 'Start with your palms facing you and rotate during the press. The rotation is the point of the exercise: without it, it becomes a regular press.'),
  (161, 'es', 'Empieza con las palmas hacia ti y gira durante la subida. La rotación es el punto del ejercicio: sin ella se vuelve un press común.'),
  (162, 'en', 'Lower the bar close to your legs by pushing your hips back. On a fixed track, standing far from the bar strains the lower back right from the start.'),
  (162, 'es', 'Baja la barra pegada a las piernas empujando la cadera hacia atrás. En el riel fijo, estar lejos de la barra fuerza la zona lumbar desde el inicio.'),
  (163, 'en', 'Feet wide, knees pointing out and grip inside your legs. Letting the knees cave in as you leave the floor overloads the knee.'),
  (163, 'es', 'Pies separados, rodillas apuntando hacia afuera y agarre por dentro de las piernas. Dejar que las rodillas caigan hacia adentro al despegar sobrecarga la rodilla.'),
  (164, 'en', 'Line up your ear, shoulder, hip and ankle. Hips high become a rest; hips low dump the load on the lower back.'),
  (164, 'es', 'Alinea oreja, hombro, cadera y tobillo. La cadera alta se vuelve descanso; la cadera baja carga la zona lumbar.'),
  (165, 'en', 'Torso leaning forward and arm parallel to the floor, extend only the forearm backward. Swinging the whole arm takes the triceps out of the movement.'),
  (165, 'es', 'Tronco inclinado y brazo paralelo al suelo, extiende solo el antebrazo hacia atrás. Balancear todo el brazo saca al tríceps del movimiento.'),
  (166, 'en', 'Your lower back cannot come off the backrest at the bottom: that is where the disc takes the load. Do not lock your knees at the end.'),
  (166, 'es', 'La zona lumbar no puede despegarse del respaldo abajo: ahí es donde el disco recibe la carga. No bloquees la rodilla al final.'),
  (167, 'en', 'Place your feet slightly ahead of the bar. The machine guides the path but does not correct a knee caving inward.'),
  (167, 'es', 'Coloca los pies un poco adelante de la barra. La máquina guía la trayectoria, pero no corrige la rodilla cayendo hacia adentro.'),
  (168, 'en', 'Back and hips flat against the backrest. If your lower back lifts off at the bottom, reduce the range.'),
  (168, 'es', 'Espalda y cadera pegadas al respaldo. Si la zona lumbar se despega abajo, reduce el recorrido.'),
  (169, 'en', 'Lower until you feel your chest stretch, without going past the line of your torso. Elbow semi-bent from start to finish.'),
  (169, 'es', 'Baja hasta sentir el estiramiento del pecho, sin pasar de la línea del tronco. Codo semiflexionado de principio a fin.'),
  (170, 'en', 'Lying on the incline bench, let your arms hang behind your torso. Bringing your elbows forward as you lift takes away the stretch that is the reason for the exercise.'),
  (170, 'es', 'Acostado en el banco inclinado, deja los brazos colgando detrás del tronco. Llevar los codos hacia adelante al subir quita el estiramiento que es la razón del ejercicio.'),
  (171, 'en', 'Pull the rope to face height, spreading your hands apart and rotating the shoulders outward. Elbow above the line of the wrist.'),
  (171, 'es', 'Tira de la cuerda a la altura de la cara, separando las manos y rotando los hombros hacia afuera. Codo por encima de la línea de la muñeca.'),
  (172, 'en', 'Ask for help getting the dumbbells into the decline position. Lower in control, without letting the shoulder roll forward.'),
  (172, 'es', 'Pide ayuda para recibir las mancuernas en la posición declinada. Baja controlado, sin dejar que el hombro ruede hacia adelante.'),
  (173, 'en', 'Holding onto the wall, bend your knee bringing your heel to your glute with the thigh still. Taking the thigh back along with it becomes glute work.'),
  (173, 'es', 'Apoyado en la pared, dobla la rodilla llevando el talón al glúteo con el muslo quieto. Llevar el muslo hacia atrás junto se vuelve trabajo de glúteo.'),
  (174, 'en', 'Rise by curling the pelvis toward the ribs, not by pulling with the legs. If your lower back arches and lifts off the support, reduce the range.'),
  (174, 'es', 'Sube enrollando la pelvis hacia las costillas, no tirando con las piernas. Si la zona lumbar se arquea y se despega del apoyo, reduce el recorrido.'),
  (175, 'en', 'Knees on the floor and torso straight from knees to head. Bending at the hips turns the push-up into an arms-only movement.'),
  (175, 'es', 'Rodillas en el suelo y tronco recto de la rodilla a la cabeza. Doblar la cadera convierte la flexión en un movimiento solo de brazos.'),
  (176, 'en', 'Feet wide with toes pointing out and knees pointing the same way. Lower between your heels keeping your torso tall.'),
  (176, 'es', 'Pies bien separados con las puntas hacia afuera y la rodilla apuntando en la misma dirección. Baja entre los talones manteniendo el tronco alto.'),
  (177, 'en', 'Hold on for balance, not to pull. Compare both sides: a big difference in reps deserves attention.'),
  (177, 'es', 'Apóyate para el equilibrio, no para tirar. Compara los dos lados: una gran diferencia de repeticiones merece atención.'),
  (178, 'en', 'Do not raise your elbow above shoulder line: that is where the shoulder pinches. Shoulder-width grip is safer than a close one.'),
  (178, 'es', 'No subas el codo por encima de la línea del hombro: ahí es donde el hombro se pellizca. Agarre al ancho de los hombros es más seguro que uno cerrado.'),
  (179, 'en', 'Elbow slightly bent and fixed; open with your shoulder blades. Going too high recruits the traps instead of the rear delt.'),
  (179, 'es', 'Codo ligeramente flexionado y fijo; abre con las escápulas. Subir demasiado recluta al trapecio en lugar del deltoides posterior.'),
  (180, 'en', 'It is a fly, not a press: the elbow does not bend to push. Heavy weight here stresses the shoulder capsule.'),
  (180, 'es', 'Es una apertura, no un press: el codo no se dobla para empujar. Un peso alto aquí estresa la cápsula del hombro.'),
  (181, 'en', 'Body straight from head to heels, pull your chest to the bar. Letting the hips sag shortens the movement and takes load off the back.'),
  (181, 'es', 'Cuerpo recto de la cabeza a los talones, lleva el pecho a la barra. Dejar caer la cadera acorta el movimiento y quita carga a la espalda.'),
  (182, 'en', 'Elbow tucked against your body and still. Only the forearm goes down and up.'),
  (182, 'es', 'Codo pegado al cuerpo e inmóvil. Solo el antebrazo baja y sube.'),
  (183, 'en', 'Hands shoulder-width apart, no closer: too narrow a grip stresses the wrist. Elbows close to your torso.'),
  (183, 'es', 'Manos al ancho de los hombros, no más cerradas: un agarre demasiado estrecho estresa la muñeca. Codos pegados al tronco.'),
  (184, 'en', 'Lower the weight with your elbow slightly bent and fixed. Your lower back cannot arch to gain range.'),
  (184, 'es', 'Baja el peso con el codo ligeramente flexionado y fijo. La zona lumbar no puede arquearse para ganar recorrido.'),
  (185, 'en', 'Facing away from the pulley, arm extended behind your torso, curl up without bringing the elbow forward. The point is the stretch at the start; shortening it wastes the exercise.'),
  (185, 'es', 'De espaldas a la polea, brazo extendido detrás del tronco, sube sin llevar el codo hacia adelante. Lo valioso es el estiramiento al inicio; acortarlo desperdicia el ejercicio.'),
  (186, 'en', 'Standing sideways to the pulley, press the cable out in front of your chest without letting your torso rotate. The exercise is about resisting rotation, not about arm strength.'),
  (186, 'es', 'De lado a la polea, empuja el cable al frente del pecho sin dejar que el tronco gire. El ejercicio consiste en resistir la rotación, no en hacer fuerza con los brazos.'),
  (187, 'en', 'One leg at a time, bend your knee bringing your heel to your glute. Moving your hips away from the machine to go higher disguises too much weight.'),
  (187, 'es', 'Una pierna a la vez, dobla la rodilla llevando el talón al glúteo. Separar la cadera de la máquina para subir más disimula demasiada carga.'),
  (188, 'en', 'Palms facing each other, lower the dumbbells beside your chest with your elbows close to your body. The grip eases the shoulder, but not lowering far enough loses the chest stretch.'),
  (188, 'es', 'Palmas enfrentadas, baja las mancuernas junto al pecho con los codos cerca del cuerpo. El agarre alivia el hombro, pero bajar poco pierde el estiramiento del pecho.'),
  (189, 'en', 'Roll out only as far as you can without your lower back giving way. Letting the hips sag is the sign the range went past the limit.'),
  (189, 'es', 'Rueda solo hasta donde puedas sin que la zona lumbar ceda. Dejar caer la cadera es la señal de que el recorrido pasó del límite.'),
  (190, 'en', 'Keep your elbows almost locked and take the bar to your thighs from the shoulder, not the elbow. Bending the arms turns it into a triceps pushdown.'),
  (190, 'es', 'Mantén los codos casi bloqueados y lleva la barra hasta los muslos desde el hombro, no desde el codo. Doblar los brazos lo convierte en un jalón de tríceps.'),
  (191, 'en', 'Adjust the seat so your elbow lines up with the machine''s axis. An elbow off the axis creates friction and loses tension midway through the movement.'),
  (191, 'es', 'Ajusta el asiento para que el codo quede alineado con el eje de la máquina. Un codo fuera del eje crea fricción y pierde tensión a mitad del movimiento.'),
  (192, 'en', 'Spread the rope ends apart as you pull down, taking your elbows to the sides of your body. Pulling with a bent wrist tires the forearm before the back.'),
  (192, 'es', 'Separa los extremos de la cuerda al bajar, llevando los codos a los lados del cuerpo. Tirar con la muñeca doblada cansa el antebrazo antes que la espalda.'),
  (193, 'en', 'Open as far as your hips allow without your torso tipping back. Return resisting, without letting the weight slam.'),
  (193, 'es', 'Abre hasta donde la cadera lo permita sin que el tronco caiga hacia atrás. Vuelve resistiendo, sin dejar que el peso golpee.'),
  (194, 'en', 'Full range: go down until stretched, up as far as you can. Bouncing at the bottom uses the tendon, not the muscle.'),
  (194, 'es', 'Recorrido completo: baja hasta estirar, sube al máximo. Rebotar abajo usa el tendón, no el músculo.'),
  (195, 'en', 'Adjust the bench so the bar passes in front of your face, not over your head. Arching your lower back to press turns it into an incline press.'),
  (195, 'es', 'Ajusta el banco para que la barra pase delante de la cara, no sobre la cabeza. Arquear la zona lumbar para empujar lo convierte en un press inclinado.'),
  (196, 'en', 'Line the handles up with mid-chest by adjusting the seat. Return slowly until you feel the stretch.'),
  (196, 'es', 'Alinea las asas con la mitad del pecho ajustando el asiento. Vuelve despacio hasta sentir el estiramiento.'),
  (197, 'en', 'Raise both dumbbells together, rotating your palms up during the lift. Bringing your elbows forward at the top takes the tension off the biceps.'),
  (197, 'es', 'Sube las dos mancuernas juntas, girando las palmas hacia arriba durante la subida. Llevar los codos hacia adelante arriba quita la tensión al bíceps.'),
  (198, 'en', 'An upright torso keeps the focus on the triceps; leaning forward shifts it to the chest. Go down until your elbow is at 90°.'),
  (198, 'es', 'El tronco vertical mantiene el foco en el tríceps; inclinarse hacia adelante lo lleva al pecho. Baja hasta que el codo quede a 90°.'),
  (199, 'en', 'Palms up, push the bar down without flaring your elbows. Use a lighter load than with the overhand grip: the wrist is more exposed.'),
  (199, 'es', 'Palmas hacia arriba, empuja la barra hacia abajo sin abrir los codos. Usa una carga menor que con el agarre prono: la muñeca queda más expuesta.'),
  (200, 'en', 'A bent knee shifts the target to the soleus: a lighter load and more reps make sense here.'),
  (200, 'es', 'La rodilla doblada cambia el objetivo al sóleo: una carga menor y más repeticiones tienen sentido aquí.'),
  (201, 'en', 'Let the dumbbells hang below your shoulders and pull toward your hips. A rounded spine in the bent-over position overloads the lower back before the back muscles.'),
  (201, 'es', 'Deja las mancuernas colgando bajo los hombros y tira hacia la cadera. La columna redondeada en la posición inclinada sobrecarga la zona lumbar antes que los músculos de la espalda.'),
  (202, 'en', 'Use a comfortable range when opening; forcing a stretch here is the most common injury on this machine. Close in control.'),
  (202, 'es', 'Usa un recorrido cómodo al abrir; forzar el estiramiento aquí es la lesión más común de esta máquina. Cierra controlado.'),
  (203, 'en', 'Steps long enough for your front knee to end up over your ankle. A short step pushes the knee too far forward and overloads the joint.'),
  (203, 'es', 'Pasos lo bastante largos para que la rodilla delantera quede sobre el tobillo. Un paso corto manda la rodilla demasiado adelante y sobrecarga la articulación.'),
  (204, 'en', 'Lower the bar only to ear level. Only do it if your shoulder rotates back without pain; the position demands more mobility than the front press.'),
  (204, 'es', 'Baja la barra solo hasta la altura de las orejas. Hazlo solo si el hombro gira hacia atrás sin dolor; la posición exige más movilidad que el press al frente.'),
  (205, 'en', 'Incline bench between the pulleys, close your arms in an arc over your chest. Letting the cables pull your arms too far back on the return strains the shoulder.'),
  (205, 'es', 'Banco inclinado entre las poleas, cierra los brazos en arco sobre el pecho. Dejar que los cables tiren los brazos demasiado hacia atrás en el regreso fuerza el hombro.'),
  (206, 'en', 'Bench between 30° and 45°; more than that becomes a shoulder press. The bar comes down at collarbone level.'),
  (206, 'es', 'Banco entre 30° y 45°; más que eso se vuelve un press de hombro. La barra baja a la altura de la clavícula.'),
  (207, 'en', 'Rise with your torso while pulling your knees to your chest, arms in front. Throwing your arms for momentum takes the work off the abs.'),
  (207, 'es', 'Sube el tronco mientras llevas las rodillas al pecho, con los brazos al frente. Lanzar los brazos para tomar impulso quita el trabajo al abdomen.'),
  (208, 'en', 'Push the platform back with your heel, torso supported and steady. Rotating your hips to go higher shifts the work to the lower back.'),
  (208, 'es', 'Empuja la plataforma hacia atrás con el talón, tronco apoyado y estable. Girar la cadera para subir más pasa el trabajo a la zona lumbar.'),
  (209, 'en', 'Raise your torso and legs together trying to touch your feet. If your lower back leaves the floor on the way down, bend your knees.'),
  (209, 'es', 'Sube tronco y piernas juntos intentando tocar los pies. Si la zona lumbar sale del suelo al bajar, dobla las rodillas.'),
  (210, 'en', 'Shoulder blades set against the bench before lifting the weight. Lower to chest level, without forcing extra range.'),
  (210, 'es', 'Escápulas encajadas en el banco antes de subir el peso. Baja hasta la línea del pecho, sin forzar recorrido extra.'),
  (211, 'en', 'Line the machine''s axis up with your shoulder joint. A short, clean movement is worth more than range with momentum.'),
  (211, 'es', 'Alinea el eje de la máquina con la articulación del hombro. Un movimiento corto y limpio vale más que recorrido con impulso.'),
  (212, 'en', 'Knee slightly bent and fixed. Lower by pushing your hips back until you feel the hamstrings stretch, without rounding your lower back.'),
  (212, 'es', 'Rodilla ligeramente flexionada y fija. Baja empujando la cadera hacia atrás hasta sentir el estiramiento de los isquiotibiales, sin redondear la zona lumbar.'),
  (213, 'en', 'Knees almost straight on the machine, rise and lower only through the ankle. Bending your knees to push turns it into a short squat.'),
  (213, 'es', 'Rodillas casi estiradas en la máquina, sube y baja solo con el tobillo. Doblar las rodillas para empujar lo convierte en una sentadilla corta.'),
  (214, 'en', 'Seven reps of the bottom half, seven of the top half and seven full ones, without rest. Use a lighter load than in the regular curl: the set is long.'),
  (214, 'es', 'Siete repeticiones de la mitad de abajo, siete de la de arriba y siete completas, sin pausa. Usa una carga menor que en el curl normal: la serie es larga.'),
  (215, 'en', 'Lift with your palms up, rotate at the top and lower with your palms down. Lowering fast loses the forearm work on the way back.'),
  (215, 'es', 'Sube con las palmas hacia arriba, gira arriba y baja con las palmas hacia abajo. Bajar rápido pierde el trabajo del antebrazo en la vuelta.'),
  (216, 'en', 'Hips flexed with a neutral spine. Lower the heel to stretch and rise to the top, without bouncing.'),
  (216, 'es', 'Cadera flexionada con la columna neutra. Baja el talón hasta estirar y sube hasta arriba, sin rebotar.'),
  (217, 'en', 'Lying face down, raise your arms and legs together and hold for a moment. Throwing your head back strains the neck without working the lower back more.'),
  (217, 'es', 'Boca abajo, eleva brazos y piernas juntos y sostén un instante. Echar la cabeza hacia atrás fuerza el cuello sin trabajar más la zona lumbar.'),
  (218, 'en', 'Lift with your elbows, not your hands, to shoulder level. Heavy weight turns it into a trap shrug.'),
  (218, 'es', 'Sube con los codos, no con las manos, hasta la línea de los hombros. Un peso alto lo convierte en un encogimiento de trapecio.')
  ),
  ordenado as (
    select id, row_number() over (order by id) as n from public.exercicio
  ),
  atualizado as (
    update public.exercicio_traducao et
       set dica_execucao = t.dica
      from t
      join ordenado o on o.n = t.n
     where et.exercicio_id = o.id and et.idioma = t.idioma
    returning 1
  )
  select count(*) into v_linhas from atualizado;

  if v_linhas <> 436 then
    raise exception 'A1: esperava 436 dicas traduzidas, atualizou %', v_linhas;
  end if;
end $$;
