-- ============================================================
-- lastro · ampliação do catálogo (pedido do dono, 2026-09-23):
-- 116 exercícios novos, catálogo de 102 para 218.
--
-- ORIGEM DA LISTA. Nomes de ficha de academia brasileira, conferidos
-- contra hasaneyldrm/exercises-dataset (MIT; é a base de onde o openGym
-- tira os exercícios). Da base só veio a conferência de que o movimento
-- existe — nome, grupo e dica são nossos. A MÍDIA da base (© Gym visual)
-- NÃO é usada aqui: exige licença própria. Proposta revisada pelo dono:
-- docs/catalogo-ampliacao-proposta.md.
--
-- Quase duplicatas deixadas de fora de propósito: tríceps pulley
-- unilateral (= Extensão de tríceps na polia alta unilateral), panturrilha
-- no degrau (= Panturrilha unilateral com halter), crucifixo máquina
-- (= Peck deck), rosca scott com barra W (= Rosca scott), mergulho para
-- peito (= Paralelas), pulldown com corda (= Pulldown braços estendidos).
--
-- GRUPO NOVO: antebraco. É "acessório" (src/lib/analise/grupos-acessorios.ts):
-- conta volume, mas só entra em grupos_sem_estimulo para quem já treinou
-- antebraço — senão toda Análise apontaria um grupo que ninguém pediu.
-- Trapézio NÃO virou grupo: encolhimentos seguem em ombro, como os que já
-- existiam, para o histórico não mudar de grupo.
--
-- unilateral: reps contadas por lado (0003). peso_por_lado: dois halteres
-- em exercício bilateral (regra da 0010); nunca junto com unilateral.
-- Dicas: escritas por Claude, origem registrada na linha (0021, FF7
-- reescrita em 2026-09-09). Nenhuma prescreve carga, séries ou progressão.
-- ============================================================

insert into public.grupo_muscular (id, nome) values ('antebraco', 'Antebraço')
on conflict (id) do nothing;

insert into public.grupo_muscular_traducao (grupo_muscular_id, idioma, nome) values
  ('antebraco', 'en', 'Forearms'),
  ('antebraco', 'es', 'Antebrazo')
on conflict (grupo_muscular_id, idioma) do nothing;

insert into public.exercicio (nome, grupo_muscular_primario, unilateral, peso_por_lado, dica_execucao, dica_execucao_origem) values
  ('Puxada triângulo', 'costas', false, false,
   'Puxe o triângulo até o alto do peito levando os cotovelos para baixo e para trás. Inclinar o tronco para trás a cada repetição transforma a puxada em remada.', 'claude'),
  ('Puxada pegada neutra', 'costas', false, false,
   'Com as palmas uma de frente para a outra, desça as pegadas até a linha do queixo. Encolher os ombros no fim tira o trabalho do dorsal e joga no trapézio.', 'claude'),
  ('Puxada unilateral no cabo', 'costas', true, false,
   'Puxe o cotovelo em direção ao quadril do mesmo lado. Girar o tronco para alcançar mais amplitude esconde a falta de força do dorsal.', 'claude'),
  ('Pulldown braços estendidos', 'costas', false, false,
   'Mantenha os cotovelos quase travados e leve a barra até as coxas pelo ombro, não pelo cotovelo. Dobrar os braços vira um tríceps pulley.', 'claude'),
  ('Barra fixa supinada', 'costas', false, false,
   'Comece com os braços estendidos e suba até o queixo passar a barra. Meias repetições no alto deixam o dorsal quase sem estímulo.', 'claude'),
  ('Barra fixa assistida máquina', 'costas', false, false,
   'Escolha a assistência que deixe as últimas repetições difíceis. Deixar a plataforma empurrar você no início do movimento tira o trabalho justamente da parte mais fraca.', 'claude'),
  ('Remada curvada supinada', 'costas', false, false,
   'Com as palmas para cima, puxe a barra até o umbigo com o tronco perto de 45 graus. Levantar o tronco a cada repetição usa a lombar como alavanca.', 'claude'),
  ('Remada curvada com halteres', 'costas', false, true,
   'Deixe os halteres pendurados abaixo dos ombros e puxe em direção ao quadril. Coluna arredondada na posição inclinada sobrecarrega a lombar antes das costas.', 'claude'),
  ('Remada no smith', 'costas', false, false,
   'Posicione o corpo para a barra subir até a parte baixa do peito. Como o trilho é fixo, ficar longe demais da barra força o puxão com os braços.', 'claude'),
  ('Remada unilateral máquina', 'costas', true, false,
   'Apoie o peito e puxe um lado de cada vez sem girar o tronco. Deixe a escápula ir à frente na volta para ganhar amplitude real.', 'claude'),
  ('Remada invertida', 'costas', false, false,
   'Corpo reto da cabeça aos calcanhares, puxe o peito até a barra. Deixar o quadril cair encurta o movimento e tira carga das costas.', 'claude'),
  ('Pull-over no cabo', 'costas', false, false,
   'Incline o tronco, braços quase estendidos, e leve a corda até as coxas num arco. Dobrar os cotovelos no meio do caminho troca dorsal por tríceps.', 'claude'),
  ('Hiperextensão lombar', 'costas', false, false,
   'Suba só até o tronco ficar alinhado com as pernas. Passar dessa linha comprime a lombar sem trabalhar mais os músculos.', 'claude'),
  ('Levantamento terra sumô', 'costas', false, false,
   'Pés afastados, joelhos apontando para fora e pegada por dentro das pernas. Deixar os joelhos caírem para dentro ao sair do chão sobrecarrega o joelho.', 'claude'),
  ('Levantamento terra com trap bar', 'costas', false, false,
   'Fique no centro da barra e empurre o chão com as pernas. Subir o quadril antes dos ombros transforma o levantamento em stiff.', 'claude'),
  ('Puxada por trás da nuca', 'costas', false, false,
   'Desça a barra só até a nuca, sem empurrar a cabeça para a frente. Só faça se o ombro tiver mobilidade para isso sem dor.', 'claude'),
  ('Puxada alta com corda', 'costas', false, false,
   'Abra as pontas da corda ao descer, levando os cotovelos para o lado do corpo. Puxar com o pulso dobrado cansa o antebraço antes das costas.', 'claude'),
  ('Remada baixa pegada aberta', 'costas', false, false,
   'Com a pegada aberta, puxe até a linha do peito com os cotovelos altos. Jogar o tronco para trás no fim só compensa carga demais.', 'claude'),
  ('Remada baixa unilateral no cabo', 'costas', true, false,
   'Puxe um braço de cada vez mantendo o peito de frente para a polia. Girar o ombro para trás rouba amplitude do dorsal.', 'claude'),
  ('Remada curvada no smith pegada supinada', 'costas', false, false,
   'Palmas para cima, puxe a barra até o umbigo com o tronco estável. Encolher os ombros ao puxar muda o alvo para o trapézio.', 'claude'),
  ('Superman', 'costas', false, false,
   'Deitado de bruços, eleve braços e pernas juntos e segure um instante. Jogar a cabeça para trás força o pescoço sem trabalhar mais a lombar.', 'claude'),
  ('Peck deck invertido', 'ombro', false, false,
   'De frente para a máquina, abra os braços até a linha dos ombros com os cotovelos levemente dobrados. Juntar as escápulas no fim vira trabalho de costas, não de deltoide posterior.', 'claude'),
  ('Crucifixo inverso no cabo', 'ombro', false, false,
   'Cabos cruzados, abra os braços na altura dos ombros. Deixar os cotovelos caírem abaixo dessa linha transforma o movimento em remada.', 'claude'),
  ('Elevação lateral no cabo', 'ombro', true, false,
   'Suba o braço pelo lado até a altura do ombro, cotovelo levemente dobrado. Inclinar o tronco para longe da polia rouba a parte difícil do movimento.', 'claude'),
  ('Elevação frontal com barra', 'ombro', false, false,
   'Suba a barra até a linha dos olhos com os braços quase estendidos. Balançar o tronco para dar impulso passa o trabalho para a lombar.', 'claude'),
  ('Elevação frontal com anilha', 'ombro', false, false,
   'Segure a anilha pelas laterais e suba até a altura dos ombros. Subir acima da cabeça não trabalha mais o deltoide e aperta o ombro.', 'claude'),
  ('Elevação frontal no cabo', 'ombro', false, false,
   'De costas para a polia, suba o cabo à frente até a linha dos ombros. Descer depressa desperdiça a tensão que o cabo dá no fim do movimento.', 'claude'),
  ('Desenvolvimento no smith', 'ombro', false, false,
   'Ajuste o banco para a barra passar à frente do rosto, não sobre a cabeça. Arquear a lombar para empurrar vira um supino inclinado.', 'claude'),
  ('Remada alta no cabo', 'ombro', false, false,
   'Puxe a barra rente ao corpo até a altura do peito, cotovelos acima dos punhos. Subir até o queixo aperta o ombro sem ganho.', 'claude'),
  ('Rotação externa no cabo', 'ombro', true, false,
   'Cotovelo colado ao corpo a 90 graus, gire o antebraço para fora. Afastar o cotovelo do tronco tira o trabalho do manguito rotador.', 'claude'),
  ('Encolhimento com barra', 'ombro', false, false,
   'Suba os ombros em direção às orelhas, reto para cima. Girar os ombros em círculo não trabalha mais o trapézio e irrita a articulação.', 'claude'),
  ('Encolhimento no smith', 'ombro', false, false,
   'Com a barra no trilho, suba os ombros e segure um instante no alto. Dobrar os cotovelos para puxar vira remada alta.', 'claude'),
  ('Desenvolvimento por trás da nuca', 'ombro', false, false,
   'Desça a barra só até a altura das orelhas. Só faça se o ombro girar para trás sem dor; a posição exige mais mobilidade que o desenvolvimento pela frente.', 'claude'),
  ('Elevação lateral unilateral inclinada', 'ombro', true, false,
   'Segure um apoio e incline o corpo para o lado oposto ao halter. Subir além da linha do ombro passa a carga para o trapézio.', 'claude'),
  ('Remada alta com halteres', 'ombro', false, true,
   'Suba os halteres rente ao corpo guiando pelos cotovelos. Levantar os punhos acima dos cotovelos tira o deltoide do movimento.', 'claude'),
  ('Desenvolvimento unilateral com halter', 'ombro', true, false,
   'Empurre um halter de cada vez sem inclinar o tronco para o lado. O abdômen segura o corpo reto, o ombro só empurra.', 'claude'),
  ('Landmine press', 'ombro', true, false,
   'Empurre a ponta da barra para cima e à frente, no arco que ela pede. Arquear a lombar para terminar o movimento esconde falta de força no ombro.', 'claude'),
  ('Supino reto no smith', 'peito', false, false,
   'Ajuste o banco para a barra descer na linha dos mamilos. Com o trilho fixo, banco mal posicionado joga a barra no pescoço ou na barriga.', 'claude'),
  ('Supino inclinado no smith', 'peito', false, false,
   'Banco entre 30 e 45 graus e a barra descendo na parte alta do peito. Tirar o quadril do banco zera a inclinação.', 'claude'),
  ('Supino declinado no smith', 'peito', false, false,
   'Prenda bem as pernas e desça a barra até a parte baixa do peito. Encurtar a descida para aguentar mais carga tira o peito do trabalho.', 'claude'),
  ('Crucifixo declinado com halteres', 'peito', false, true,
   'Abra os braços num arco até sentir o peito alongar, cotovelos levemente dobrados. Descer abaixo da linha do banco estressa o ombro.', 'claude'),
  ('Crossover polia baixa', 'peito', false, false,
   'Com as polias embaixo, suba os braços em arco até a altura do peito. Dobrar os cotovelos no caminho vira elevação frontal.', 'claude'),
  ('Crucifixo inclinado no cabo', 'peito', false, false,
   'Banco inclinado entre as polias, feche os braços em arco sobre o peito. Deixar os cabos puxarem os braços para trás demais no retorno força o ombro.', 'claude'),
  ('Supino com halteres pegada neutra', 'peito', false, true,
   'Palmas uma de frente para a outra, desça os halteres ao lado do peito com os cotovelos perto do corpo. A pegada alivia o ombro, mas descer pouco perde o alongamento do peito.', 'claude'),
  ('Flexão de braço declinada', 'peito', false, false,
   'Pés elevados no banco, desça o peito até perto do chão com o corpo reto. Deixar o quadril subir tira carga do peito.', 'claude'),
  ('Flexão de braço inclinada', 'peito', false, false,
   'Mãos no banco, desça até o peito encostar nele. É a progressão da flexão: quanto mais alto o apoio, mais fácil.', 'claude'),
  ('Flexão de braço com joelhos apoiados', 'peito', false, false,
   'Joelhos no chão e tronco reto do joelho à cabeça. Dobrar no quadril transforma a flexão num movimento só de braço.', 'claude'),
  ('Rosca direta com barra W', 'biceps', false, false,
   'Cotovelos parados ao lado do corpo, suba a barra até o bíceps contrair. Balançar o tronco para subir passa a carga para as costas.', 'claude'),
  ('Rosca scott unilateral com halter', 'biceps', true, false,
   'Braço inteiro apoiado no banco, desça até quase estender. Soltar o halter no fim da descida é quando o bíceps mais se machuca.', 'claude'),
  ('Rosca scott máquina', 'biceps', false, false,
   'Ajuste o assento para o cotovelo ficar alinhado com o eixo da máquina. Cotovelo fora do eixo cria atrito e perde tensão no meio do movimento.', 'claude'),
  ('Rosca inclinada com halteres', 'biceps', false, true,
   'Deitado no banco inclinado, deixe os braços pendurados atrás do tronco. Trazer os cotovelos para a frente ao subir tira o alongamento que é o motivo do exercício.', 'claude'),
  ('Rosca martelo no cabo (corda)', 'biceps', false, false,
   'Polegares para cima, suba a corda sem afastar os cotovelos do corpo. Puxar com o ombro no fim encurta o trabalho do braquial.', 'claude'),
  ('Rosca unilateral no cabo', 'biceps', true, false,
   'Um braço de cada vez, cotovelo fixo ao lado do corpo. Girar o tronco para acompanhar o cabo esconde a falta de força do bíceps.', 'claude'),
  ('Rosca 21', 'biceps', false, false,
   'Sete repetições da metade de baixo, sete da de cima e sete completas, sem pausa. Use carga menor que a da rosca direta: a série é longa.', 'claude'),
  ('Rosca direta com halteres', 'biceps', false, true,
   'Suba os dois halteres juntos, girando as palmas para cima durante a subida. Levar os cotovelos à frente no alto tira a tensão do bíceps.', 'claude'),
  ('Rosca martelo alternada', 'biceps', true, false,
   'Um braço de cada vez, polegar para cima o tempo todo. Balançar o corpo para subir o halter mostra carga demais.', 'claude'),
  ('Rosca bayesiana no cabo', 'biceps', true, false,
   'De costas para a polia, braço estendido atrás do tronco, suba sem trazer o cotovelo à frente. A graça é o alongamento no início; encurtá-lo desperdiça o exercício.', 'claude'),
  ('Rosca Zottman', 'biceps', true, false,
   'Suba com as palmas para cima, gire no alto e desça com as palmas para baixo. Descer depressa perde o trabalho do antebraço na volta.', 'claude'),
  ('Tríceps pulley barra reta', 'triceps', false, false,
   'Cotovelos colados ao corpo, estenda até travar o braço. Deixar os cotovelos subirem na volta transforma o pulley em puxada.', 'claude'),
  ('Tríceps pulley pegada supinada', 'triceps', false, false,
   'Palmas para cima, empurre a barra para baixo sem abrir os cotovelos. Use carga menor que na pegada pronada; o punho fica mais exposto.', 'claude'),
  ('Tríceps francês no cabo (corda)', 'triceps', false, false,
   'De costas para a polia, cotovelos apontando para a frente, estenda a corda acima da cabeça. Abrir os cotovelos para os lados passa a força para o ombro.', 'claude'),
  ('Tríceps testa com barra W', 'triceps', false, false,
   'Desça a barra em direção à testa só dobrando o cotovelo. Mover o braço junto na descida vira pullover e tira carga do tríceps.', 'claude'),
  ('Tríceps testa com halteres', 'triceps', false, true,
   'Palmas viradas uma para a outra, desça os halteres ao lado da cabeça. Cotovelos abrindo para fora aliviam o tríceps e forçam o cotovelo.', 'claude'),
  ('Tríceps coice no cabo', 'triceps', true, false,
   'Tronco inclinado e braço paralelo ao chão, estenda só o antebraço para trás. Balançar o braço inteiro tira o tríceps do movimento.', 'claude'),
  ('Flexão diamante', 'triceps', false, false,
   'Mãos juntas formando um losango sob o peito, cotovelos rentes ao corpo. Se o punho doer, afaste um pouco as mãos.', 'claude'),
  ('Tríceps francês com barra W', 'triceps', false, false,
   'Sentado com apoio nas costas, desça a barra atrás da cabeça só com o cotovelo. Arquear a lombar para subir mostra carga demais.', 'claude'),
  ('Tríceps testa no cabo', 'triceps', false, false,
   'Deitado com a cabeça voltada para a polia, estenda a barra acima do peito. O cabo mantém tensão no alto; não descanse com os braços travados.', 'claude'),
  ('Agachamento goblet', 'quadriceps', false, false,
   'Segure o halter junto ao peito e desça com o tronco em pé, joelhos seguindo a ponta dos pés. Deixar o halter afastar do corpo puxa o tronco para a frente.', 'claude'),
  ('Agachamento pendular', 'quadriceps', false, false,
   'Costas coladas no apoio e pés no meio da plataforma, desça até o fim do trajeto. Tirar o quadril do encosto no fundo passa a carga para a lombar.', 'claude'),
  ('Agachamento sissy', 'quadriceps', false, false,
   'Com apoio para as mãos, leve os joelhos à frente e o tronco para trás numa linha reta. Dobrar no quadril transforma o sissy num agachamento comum.', 'claude'),
  ('Afundo reverso', 'quadriceps', true, false,
   'Dê o passo para trás e desça até o joelho de trás quase tocar o chão. O peso fica no calcanhar da perna da frente, não na ponta do pé.', 'claude'),
  ('Passada andando com halteres', 'quadriceps', true, false,
   'Passos longos o bastante para o joelho da frente ficar sobre o tornozelo. Passo curto joga o joelho muito à frente e sobrecarrega a articulação.', 'claude'),
  ('Afundo no smith', 'quadriceps', true, false,
   'Posicione o pé da frente adiante da barra para descer reto. Com o trilho fixo, pé mal colocado força o joelho a passar muito da ponta do pé.', 'claude'),
  ('Cadeira extensora unilateral', 'quadriceps', true, false,
   'Uma perna de cada vez, estenda até quase travar e desça devagar. Segurar o banco com força para levantar o quadril compensa carga demais.', 'claude'),
  ('Agachamento com halteres', 'quadriceps', false, true,
   'Halteres ao lado do corpo, desça mantendo o peito aberto. Deixar os ombros rolarem para a frente arredonda as costas.', 'claude'),
  ('Agachamento búlgaro no smith', 'quadriceps', true, false,
   'Pé de trás no banco e pé da frente adiante da barra, desça reto no trilho. Empurre pelo calcanhar da frente; a perna de trás só equilibra.', 'claude'),
  ('Afundo com barra', 'quadriceps', true, false,
   'Barra nas costas, passo firme à frente e tronco em pé. Passo estreito, pé atrás do pé, tira o equilíbrio e trava o movimento.', 'claude'),
  ('Agachamento frontal no smith', 'quadriceps', false, false,
   'Barra apoiada na frente dos ombros, cotovelos altos, desça com o tronco em pé. Cotovelos caindo deixam a barra escorregar para os punhos.', 'claude'),
  ('Agachamento isométrico na parede', 'quadriceps', false, false,
   'Costas na parede e joelhos a 90 graus, com o peso nos calcanhares. Apoiar as mãos nas coxas alivia justamente o quadríceps que o exercício quer cansar.', 'claude'),
  ('Stiff com halteres', 'posterior_coxa', false, true,
   'Joelhos quase estendidos, desça os halteres rente às pernas levando o quadril para trás. Arredondar a coluna para descer mais sobrecarrega a lombar.', 'claude'),
  ('Levantamento terra romeno com barra', 'posterior_coxa', false, false,
   'Joelhos levemente dobrados, empurre o quadril para trás até sentir o posterior esticar. Descer além disso arredondando as costas não trabalha mais o posterior.', 'claude'),
  ('Stiff unilateral com halter', 'posterior_coxa', true, false,
   'Apoiado numa perna, incline o tronco enquanto a outra perna sobe atrás. Abrir o quadril para o lado tira o equilíbrio e o trabalho do posterior.', 'claude'),
  ('Flexora em pé máquina', 'posterior_coxa', true, false,
   'Uma perna de cada vez, dobre o joelho trazendo o calcanhar ao glúteo. Afastar o quadril da máquina para subir mais disfarça carga demais.', 'claude'),
  ('Flexão nórdica', 'posterior_coxa', false, false,
   'Tornozelos presos, desça o tronco à frente o mais devagar que conseguir. Dobrar no quadril na descida tira o posterior do trabalho.', 'claude'),
  ('Stiff no smith', 'posterior_coxa', false, false,
   'Desça a barra rente às pernas empurrando o quadril para trás. No trilho fixo, ficar longe da barra força a lombar logo no início.', 'claude'),
  ('Flexão de joelho com caneleira em pé', 'posterior_coxa', true, false,
   'Apoiado na parede, dobre o joelho levando o calcanhar ao glúteo com a coxa parada. Levar a coxa para trás junto vira trabalho de glúteo.', 'claude'),
  ('Glúteo quatro apoios', 'gluteo', true, false,
   'Em quatro apoios, suba a perna até a coxa ficar alinhada com o tronco. Arquear a lombar para subir mais tira o glúteo do movimento.', 'claude'),
  ('Glúteo máquina (coice)', 'gluteo', true, false,
   'Empurre a plataforma para trás com o calcanhar, tronco apoiado e estável. Girar o quadril para subir mais passa o trabalho para a lombar.', 'claude'),
  ('Elevação pélvica no smith', 'gluteo', false, false,
   'Costas no banco e barra no quadril, suba até o tronco ficar paralelo ao chão. Arquear a lombar no alto parece mais amplitude mas não é glúteo.', 'claude'),
  ('Abdução de quadril no cabo', 'gluteo', true, false,
   'Tornozeleira no pé de fora, leve a perna para o lado com o tronco reto. Inclinar o corpo para o lado oposto rouba amplitude do glúteo.', 'claude'),
  ('Adução de quadril no cabo', 'gluteo', true, false,
   'Tornozeleira no pé de dentro, traga a perna à frente da outra. Balançar a perna para ganhar impulso tira a tensão do adutor.', 'claude'),
  ('Agachamento sumô com barra', 'gluteo', false, false,
   'Pés bem afastados e virados para fora, joelhos acompanhando os pés. Joelhos fechando para dentro na subida sobrecarregam a articulação.', 'claude'),
  ('Agachamento sumô no smith', 'gluteo', false, false,
   'Pés afastados e à frente da barra, desça com o tronco em pé. Pés muito para trás tiram o glúteo e jogam a carga no joelho.', 'claude'),
  ('Afundo cruzado', 'gluteo', true, false,
   'Leve a perna de trás cruzando atrás da da frente e desça. O joelho da frente segue a ponta do pé; deixá-lo cair para dentro é o erro comum.', 'claude'),
  ('Abdução deitado com caneleira', 'gluteo', true, false,
   'Deitado de lado, suba a perna de cima levemente para trás, não para a frente. Levar a perna à frente passa o trabalho para o flexor do quadril.', 'claude'),
  ('Caminhada lateral com mini band', 'gluteo', false, false,
   'Semiagachado, dê passos laterais sem deixar os pés se juntarem. Ficar em pé demais tira a tensão do glúteo médio.', 'claude'),
  ('Panturrilha no smith', 'panturrilha', false, false,
   'Ponta dos pés num degrau, desça o calcanhar abaixo do degrau e suba até a ponta. Meias repetições rápidas no alto deixam a panturrilha quase sem estímulo.', 'claude'),
  ('Panturrilha no hack', 'panturrilha', false, false,
   'Joelhos quase estendidos na máquina, suba e desça só pelo tornozelo. Dobrar o joelho para empurrar vira agachamento curto.', 'claude'),
  ('Abdominal canivete', 'abdomen', false, false,
   'Suba tronco e pernas juntos tentando tocar os pés. Se a lombar sair do chão ao descer, dobre os joelhos.', 'claude'),
  ('Abdominal na roda', 'abdomen', false, false,
   'Role só até onde consegue sem a lombar ceder. Deixar o quadril cair é o sinal de que a amplitude passou do ponto.', 'claude'),
  ('Elevação de pernas na barra', 'abdomen', false, false,
   'Pendurado na barra, suba as pernas enrolando a pelve, sem balançar. Subir só as pernas sem enrolar a pelve trabalha mais o flexor do quadril.', 'claude'),
  ('Abdominal declinado', 'abdomen', false, false,
   'Pés presos no banco declinado, enrole o tronco vértebra por vértebra. Puxar a cabeça com as mãos força o pescoço.', 'claude'),
  ('Giro russo', 'abdomen', false, false,
   'Tronco inclinado para trás, gire os ombros de um lado ao outro, não só os braços. Mover só as mãos deixa o oblíquo parado.', 'claude'),
  ('Escalador', 'abdomen', false, false,
   'Em prancha alta, traga os joelhos ao peito alternando, quadril na linha dos ombros. Subir o quadril facilita e tira o abdômen do trabalho.', 'claude'),
  ('Pallof press', 'abdomen', true, false,
   'De lado para a polia, empurre o cabo à frente do peito sem deixar o tronco girar. O exercício é resistir à rotação, não fazer força com os braços.', 'claude'),
  ('Abdominal remador', 'abdomen', false, false,
   'Suba o tronco enquanto puxa os joelhos ao peito, braços à frente. Jogar os braços para dar impulso tira o trabalho do abdômen.', 'claude'),
  ('Abdominal infra tesourinha', 'abdomen', false, false,
   'Deitado, alterne as pernas estendidas perto do chão. Se a lombar descolar, suba mais as pernas.', 'claude'),
  ('Elevação de joelhos na paralela', 'abdomen', false, false,
   'Antebraços apoiados e costas no encosto, traga os joelhos ao peito enrolando a pelve. Balançar as pernas para subir gasta impulso, não abdômen.', 'claude'),
  ('Flexão lateral com halter', 'abdomen', true, false,
   'Halter em uma mão, incline o tronco para o lado dele e volte. Segurar halter nas duas mãos anula o exercício, um lado equilibra o outro.', 'claude'),
  ('Abdominal com anilha', 'abdomen', false, false,
   'Anilha no peito, enrole o tronco sem tirar a lombar do chão. Segurar a anilha atrás da cabeça força o pescoço.', 'claude'),
  ('Dead bug', 'abdomen', false, false,
   'Deitado, estenda braço e perna opostos devagar mantendo a lombar colada ao chão. Se ela descolar, encurte a amplitude.', 'claude'),
  ('Rosca de punho com barra', 'antebraco', false, false,
   'Antebraços apoiados na coxa ou no banco, palmas para cima, suba só o punho. Levantar o antebraço do apoio transforma o exercício em rosca.', 'claude'),
  ('Rosca de punho inversa', 'antebraco', false, false,
   'Palmas para baixo e antebraços apoiados, suba o dorso da mão. A carga é bem menor que na rosca de punho comum.', 'claude'),
  ('Rosca de punho com halter', 'antebraco', true, false,
   'Um punho de cada vez, antebraço apoiado, suba e desça só a mão. Deixar o halter rolar até a ponta dos dedos é opcional, mas faça devagar.', 'claude'),
  ('Caminhada do fazendeiro', 'antebraco', false, true,
   'Halteres pesados nas mãos, caminhe em passos curtos com os ombros para trás e o tronco em pé. Deixar os ombros caírem para a frente transfere a carga para a lombar.', 'claude'),
  ('Rolo de punho', 'antebraco', false, false,
   'Braços estendidos à frente, enrole a corda até a carga subir e desenrole devagar. Descer os braços durante a série tira o trabalho do antebraço.', 'claude')
on conflict (nome) do nothing;

insert into public.exercicio_traducao (exercicio_id, idioma, nome)
select e.id, v.idioma, v.nome
from (values
  ('Puxada triângulo', 'en', 'V-Bar Lat Pulldown'),
  ('Puxada triângulo', 'es', 'Jalón con triángulo'),
  ('Puxada pegada neutra', 'en', 'Neutral-Grip Lat Pulldown'),
  ('Puxada pegada neutra', 'es', 'Jalón con agarre neutro'),
  ('Puxada unilateral no cabo', 'en', 'Single-Arm Cable Pulldown'),
  ('Puxada unilateral no cabo', 'es', 'Jalón unilateral en polea'),
  ('Pulldown braços estendidos', 'en', 'Straight-Arm Pulldown'),
  ('Pulldown braços estendidos', 'es', 'Pulldown con brazos extendidos'),
  ('Barra fixa supinada', 'en', 'Chin-Up'),
  ('Barra fixa supinada', 'es', 'Dominada supina'),
  ('Barra fixa assistida máquina', 'en', 'Assisted Pull-Up Machine'),
  ('Barra fixa assistida máquina', 'es', 'Dominada asistida en máquina'),
  ('Remada curvada supinada', 'en', 'Reverse-Grip Barbell Row'),
  ('Remada curvada supinada', 'es', 'Remo con barra agarre supino'),
  ('Remada curvada com halteres', 'en', 'Dumbbell Bent-Over Row'),
  ('Remada curvada com halteres', 'es', 'Remo inclinado con mancuernas'),
  ('Remada no smith', 'en', 'Smith Machine Row'),
  ('Remada no smith', 'es', 'Remo en máquina Smith'),
  ('Remada unilateral máquina', 'en', 'Single-Arm Machine Row'),
  ('Remada unilateral máquina', 'es', 'Remo unilateral en máquina'),
  ('Remada invertida', 'en', 'Inverted Row'),
  ('Remada invertida', 'es', 'Remo invertido'),
  ('Pull-over no cabo', 'en', 'Cable Pullover'),
  ('Pull-over no cabo', 'es', 'Pullover en polea'),
  ('Hiperextensão lombar', 'en', 'Back Extension'),
  ('Hiperextensão lombar', 'es', 'Hiperextensión lumbar'),
  ('Levantamento terra sumô', 'en', 'Sumo Deadlift'),
  ('Levantamento terra sumô', 'es', 'Peso muerto sumo'),
  ('Levantamento terra com trap bar', 'en', 'Trap Bar Deadlift'),
  ('Levantamento terra com trap bar', 'es', 'Peso muerto con barra hexagonal'),
  ('Puxada por trás da nuca', 'en', 'Behind-the-Neck Lat Pulldown'),
  ('Puxada por trás da nuca', 'es', 'Jalón tras nuca'),
  ('Puxada alta com corda', 'en', 'Rope Lat Pulldown'),
  ('Puxada alta com corda', 'es', 'Jalón con cuerda'),
  ('Remada baixa pegada aberta', 'en', 'Wide-Grip Seated Cable Row'),
  ('Remada baixa pegada aberta', 'es', 'Remo sentado agarre ancho'),
  ('Remada baixa unilateral no cabo', 'en', 'Single-Arm Seated Cable Row'),
  ('Remada baixa unilateral no cabo', 'es', 'Remo sentado unilateral en polea'),
  ('Remada curvada no smith pegada supinada', 'en', 'Smith Machine Reverse-Grip Row'),
  ('Remada curvada no smith pegada supinada', 'es', 'Remo supino en máquina Smith'),
  ('Superman', 'en', 'Superman'),
  ('Superman', 'es', 'Superman'),
  ('Peck deck invertido', 'en', 'Reverse Pec Deck'),
  ('Peck deck invertido', 'es', 'Pec deck invertido'),
  ('Crucifixo inverso no cabo', 'en', 'Cable Reverse Fly'),
  ('Crucifixo inverso no cabo', 'es', 'Aperturas inversas en polea'),
  ('Elevação lateral no cabo', 'en', 'Single-Arm Cable Lateral Raise'),
  ('Elevação lateral no cabo', 'es', 'Elevación lateral en polea'),
  ('Elevação frontal com barra', 'en', 'Barbell Front Raise'),
  ('Elevação frontal com barra', 'es', 'Elevación frontal con barra'),
  ('Elevação frontal com anilha', 'en', 'Plate Front Raise'),
  ('Elevação frontal com anilha', 'es', 'Elevación frontal con disco'),
  ('Elevação frontal no cabo', 'en', 'Cable Front Raise'),
  ('Elevação frontal no cabo', 'es', 'Elevación frontal en polea'),
  ('Desenvolvimento no smith', 'en', 'Smith Machine Shoulder Press'),
  ('Desenvolvimento no smith', 'es', 'Press militar en máquina Smith'),
  ('Remada alta no cabo', 'en', 'Cable Upright Row'),
  ('Remada alta no cabo', 'es', 'Remo al mentón en polea'),
  ('Rotação externa no cabo', 'en', 'Cable External Rotation'),
  ('Rotação externa no cabo', 'es', 'Rotación externa en polea'),
  ('Encolhimento com barra', 'en', 'Barbell Shrug'),
  ('Encolhimento com barra', 'es', 'Encogimiento con barra'),
  ('Encolhimento no smith', 'en', 'Smith Machine Shrug'),
  ('Encolhimento no smith', 'es', 'Encogimiento en máquina Smith'),
  ('Desenvolvimento por trás da nuca', 'en', 'Behind-the-Neck Press'),
  ('Desenvolvimento por trás da nuca', 'es', 'Press tras nuca'),
  ('Elevação lateral unilateral inclinada', 'en', 'Leaning Single-Arm Lateral Raise'),
  ('Elevação lateral unilateral inclinada', 'es', 'Elevación lateral unilateral inclinada'),
  ('Remada alta com halteres', 'en', 'Dumbbell Upright Row'),
  ('Remada alta com halteres', 'es', 'Remo al mentón con mancuernas'),
  ('Desenvolvimento unilateral com halter', 'en', 'Single-Arm Dumbbell Shoulder Press'),
  ('Desenvolvimento unilateral com halter', 'es', 'Press de hombro unilateral con mancuerna'),
  ('Landmine press', 'en', 'Landmine Press'),
  ('Landmine press', 'es', 'Press landmine'),
  ('Supino reto no smith', 'en', 'Smith Machine Bench Press'),
  ('Supino reto no smith', 'es', 'Press de banca en máquina Smith'),
  ('Supino inclinado no smith', 'en', 'Smith Machine Incline Bench Press'),
  ('Supino inclinado no smith', 'es', 'Press inclinado en máquina Smith'),
  ('Supino declinado no smith', 'en', 'Smith Machine Decline Bench Press'),
  ('Supino declinado no smith', 'es', 'Press declinado en máquina Smith'),
  ('Crucifixo declinado com halteres', 'en', 'Decline Dumbbell Fly'),
  ('Crucifixo declinado com halteres', 'es', 'Aperturas declinadas con mancuernas'),
  ('Crossover polia baixa', 'en', 'Low-to-High Cable Fly'),
  ('Crossover polia baixa', 'es', 'Cruce de poleas bajo'),
  ('Crucifixo inclinado no cabo', 'en', 'Incline Cable Fly'),
  ('Crucifixo inclinado no cabo', 'es', 'Aperturas inclinadas en polea'),
  ('Supino com halteres pegada neutra', 'en', 'Neutral-Grip Dumbbell Press'),
  ('Supino com halteres pegada neutra', 'es', 'Press con mancuernas agarre neutro'),
  ('Flexão de braço declinada', 'en', 'Decline Push-Up'),
  ('Flexão de braço declinada', 'es', 'Flexión declinada'),
  ('Flexão de braço inclinada', 'en', 'Incline Push-Up'),
  ('Flexão de braço inclinada', 'es', 'Flexión inclinada'),
  ('Flexão de braço com joelhos apoiados', 'en', 'Knee Push-Up'),
  ('Flexão de braço com joelhos apoiados', 'es', 'Flexión con rodillas apoyadas'),
  ('Rosca direta com barra W', 'en', 'EZ-Bar Curl'),
  ('Rosca direta com barra W', 'es', 'Curl con barra Z'),
  ('Rosca scott unilateral com halter', 'en', 'Single-Arm Dumbbell Preacher Curl'),
  ('Rosca scott unilateral com halter', 'es', 'Curl predicador unilateral con mancuerna'),
  ('Rosca scott máquina', 'en', 'Machine Preacher Curl'),
  ('Rosca scott máquina', 'es', 'Curl predicador en máquina'),
  ('Rosca inclinada com halteres', 'en', 'Incline Dumbbell Curl'),
  ('Rosca inclinada com halteres', 'es', 'Curl inclinado con mancuernas'),
  ('Rosca martelo no cabo (corda)', 'en', 'Cable Rope Hammer Curl'),
  ('Rosca martelo no cabo (corda)', 'es', 'Curl martillo en polea con cuerda'),
  ('Rosca unilateral no cabo', 'en', 'Single-Arm Cable Curl'),
  ('Rosca unilateral no cabo', 'es', 'Curl unilateral en polea'),
  ('Rosca 21', 'en', '21s Curl'),
  ('Rosca 21', 'es', 'Curl 21'),
  ('Rosca direta com halteres', 'en', 'Dumbbell Curl'),
  ('Rosca direta com halteres', 'es', 'Curl con mancuernas'),
  ('Rosca martelo alternada', 'en', 'Alternating Hammer Curl'),
  ('Rosca martelo alternada', 'es', 'Curl martillo alterno'),
  ('Rosca bayesiana no cabo', 'en', 'Bayesian Cable Curl'),
  ('Rosca bayesiana no cabo', 'es', 'Curl bayesiano en polea'),
  ('Rosca Zottman', 'en', 'Zottman Curl'),
  ('Rosca Zottman', 'es', 'Curl Zottman'),
  ('Tríceps pulley barra reta', 'en', 'Straight-Bar Triceps Pushdown'),
  ('Tríceps pulley barra reta', 'es', 'Extensión de tríceps en polea con barra'),
  ('Tríceps pulley pegada supinada', 'en', 'Reverse-Grip Triceps Pushdown'),
  ('Tríceps pulley pegada supinada', 'es', 'Extensión de tríceps agarre supino'),
  ('Tríceps francês no cabo (corda)', 'en', 'Overhead Cable Triceps Extension'),
  ('Tríceps francês no cabo (corda)', 'es', 'Extensión de tríceps sobre la cabeza en polea'),
  ('Tríceps testa com barra W', 'en', 'EZ-Bar Skull Crusher'),
  ('Tríceps testa com barra W', 'es', 'Press francés con barra Z'),
  ('Tríceps testa com halteres', 'en', 'Dumbbell Skull Crusher'),
  ('Tríceps testa com halteres', 'es', 'Press francés con mancuernas'),
  ('Tríceps coice no cabo', 'en', 'Cable Triceps Kickback'),
  ('Tríceps coice no cabo', 'es', 'Patada de tríceps en polea'),
  ('Flexão diamante', 'en', 'Diamond Push-Up'),
  ('Flexão diamante', 'es', 'Flexión diamante'),
  ('Tríceps francês com barra W', 'en', 'EZ-Bar Overhead Triceps Extension'),
  ('Tríceps francês com barra W', 'es', 'Extensión de tríceps sobre la cabeza con barra Z'),
  ('Tríceps testa no cabo', 'en', 'Cable Skull Crusher'),
  ('Tríceps testa no cabo', 'es', 'Press francés en polea'),
  ('Agachamento goblet', 'en', 'Goblet Squat'),
  ('Agachamento goblet', 'es', 'Sentadilla goblet'),
  ('Agachamento pendular', 'en', 'Pendulum Squat'),
  ('Agachamento pendular', 'es', 'Sentadilla pendular'),
  ('Agachamento sissy', 'en', 'Sissy Squat'),
  ('Agachamento sissy', 'es', 'Sentadilla sissy'),
  ('Afundo reverso', 'en', 'Reverse Lunge'),
  ('Afundo reverso', 'es', 'Zancada inversa'),
  ('Passada andando com halteres', 'en', 'Dumbbell Walking Lunge'),
  ('Passada andando com halteres', 'es', 'Zancadas caminando con mancuernas'),
  ('Afundo no smith', 'en', 'Smith Machine Split Squat'),
  ('Afundo no smith', 'es', 'Zancada en máquina Smith'),
  ('Cadeira extensora unilateral', 'en', 'Single-Leg Leg Extension'),
  ('Cadeira extensora unilateral', 'es', 'Extensión de cuádriceps unilateral'),
  ('Agachamento com halteres', 'en', 'Dumbbell Squat'),
  ('Agachamento com halteres', 'es', 'Sentadilla con mancuernas'),
  ('Agachamento búlgaro no smith', 'en', 'Smith Machine Bulgarian Split Squat'),
  ('Agachamento búlgaro no smith', 'es', 'Sentadilla búlgara en máquina Smith'),
  ('Afundo com barra', 'en', 'Barbell Lunge'),
  ('Afundo com barra', 'es', 'Zancada con barra'),
  ('Agachamento frontal no smith', 'en', 'Smith Machine Front Squat'),
  ('Agachamento frontal no smith', 'es', 'Sentadilla frontal en máquina Smith'),
  ('Agachamento isométrico na parede', 'en', 'Wall Sit'),
  ('Agachamento isométrico na parede', 'es', 'Sentadilla isométrica en pared'),
  ('Stiff com halteres', 'en', 'Dumbbell Stiff-Leg Deadlift'),
  ('Stiff com halteres', 'es', 'Peso muerto piernas rígidas con mancuernas'),
  ('Levantamento terra romeno com barra', 'en', 'Barbell Romanian Deadlift'),
  ('Levantamento terra romeno com barra', 'es', 'Peso muerto rumano con barra'),
  ('Stiff unilateral com halter', 'en', 'Single-Leg Dumbbell Romanian Deadlift'),
  ('Stiff unilateral com halter', 'es', 'Peso muerto rumano a una pierna con mancuerna'),
  ('Flexora em pé máquina', 'en', 'Standing Leg Curl Machine'),
  ('Flexora em pé máquina', 'es', 'Curl femoral de pie en máquina'),
  ('Flexão nórdica', 'en', 'Nordic Hamstring Curl'),
  ('Flexão nórdica', 'es', 'Curl nórdico'),
  ('Stiff no smith', 'en', 'Smith Machine Stiff-Leg Deadlift'),
  ('Stiff no smith', 'es', 'Peso muerto piernas rígidas en máquina Smith'),
  ('Flexão de joelho com caneleira em pé', 'en', 'Standing Ankle-Weight Leg Curl'),
  ('Flexão de joelho com caneleira em pé', 'es', 'Curl femoral de pie con tobillera'),
  ('Glúteo quatro apoios', 'en', 'Quadruped Hip Extension'),
  ('Glúteo quatro apoios', 'es', 'Patada de glúteo en cuadrupedia'),
  ('Glúteo máquina (coice)', 'en', 'Glute Kickback Machine'),
  ('Glúteo máquina (coice)', 'es', 'Patada de glúteo en máquina'),
  ('Elevação pélvica no smith', 'en', 'Smith Machine Hip Thrust'),
  ('Elevação pélvica no smith', 'es', 'Hip thrust en máquina Smith'),
  ('Abdução de quadril no cabo', 'en', 'Cable Hip Abduction'),
  ('Abdução de quadril no cabo', 'es', 'Abducción de cadera en polea'),
  ('Adução de quadril no cabo', 'en', 'Cable Hip Adduction'),
  ('Adução de quadril no cabo', 'es', 'Aducción de cadera en polea'),
  ('Agachamento sumô com barra', 'en', 'Barbell Sumo Squat'),
  ('Agachamento sumô com barra', 'es', 'Sentadilla sumo con barra'),
  ('Agachamento sumô no smith', 'en', 'Smith Machine Sumo Squat'),
  ('Agachamento sumô no smith', 'es', 'Sentadilla sumo en máquina Smith'),
  ('Afundo cruzado', 'en', 'Curtsy Lunge'),
  ('Afundo cruzado', 'es', 'Zancada cruzada'),
  ('Abdução deitado com caneleira', 'en', 'Side-Lying Hip Abduction'),
  ('Abdução deitado com caneleira', 'es', 'Abducción de cadera tumbado con tobillera'),
  ('Caminhada lateral com mini band', 'en', 'Mini-Band Lateral Walk'),
  ('Caminhada lateral com mini band', 'es', 'Caminata lateral con mini banda'),
  ('Panturrilha no smith', 'en', 'Smith Machine Calf Raise'),
  ('Panturrilha no smith', 'es', 'Elevación de talones en máquina Smith'),
  ('Panturrilha no hack', 'en', 'Hack Machine Calf Raise'),
  ('Panturrilha no hack', 'es', 'Elevación de talones en máquina hack'),
  ('Abdominal canivete', 'en', 'V-Up'),
  ('Abdominal canivete', 'es', 'Abdominal en V'),
  ('Abdominal na roda', 'en', 'Ab Wheel Rollout'),
  ('Abdominal na roda', 'es', 'Rueda abdominal'),
  ('Elevação de pernas na barra', 'en', 'Hanging Leg Raise'),
  ('Elevação de pernas na barra', 'es', 'Elevación de piernas colgado'),
  ('Abdominal declinado', 'en', 'Decline Sit-Up'),
  ('Abdominal declinado', 'es', 'Abdominal declinado'),
  ('Giro russo', 'en', 'Russian Twist'),
  ('Giro russo', 'es', 'Giro ruso'),
  ('Escalador', 'en', 'Mountain Climber'),
  ('Escalador', 'es', 'Escalador'),
  ('Pallof press', 'en', 'Pallof Press'),
  ('Pallof press', 'es', 'Press Pallof'),
  ('Abdominal remador', 'en', 'Tuck Sit-Up'),
  ('Abdominal remador', 'es', 'Abdominal remador'),
  ('Abdominal infra tesourinha', 'en', 'Flutter Kicks'),
  ('Abdominal infra tesourinha', 'es', 'Tijeras abdominales'),
  ('Elevação de joelhos na paralela', 'en', 'Captain''s Chair Knee Raise'),
  ('Elevação de joelhos na paralela', 'es', 'Elevación de rodillas en paralelas'),
  ('Flexão lateral com halter', 'en', 'Dumbbell Side Bend'),
  ('Flexão lateral com halter', 'es', 'Flexión lateral con mancuerna'),
  ('Abdominal com anilha', 'en', 'Weighted Crunch'),
  ('Abdominal com anilha', 'es', 'Abdominal con disco'),
  ('Dead bug', 'en', 'Dead Bug'),
  ('Dead bug', 'es', 'Dead bug'),
  ('Rosca de punho com barra', 'en', 'Barbell Wrist Curl'),
  ('Rosca de punho com barra', 'es', 'Curl de muñeca con barra'),
  ('Rosca de punho inversa', 'en', 'Reverse Barbell Wrist Curl'),
  ('Rosca de punho inversa', 'es', 'Curl de muñeca inverso con barra'),
  ('Rosca de punho com halter', 'en', 'Dumbbell Wrist Curl'),
  ('Rosca de punho com halter', 'es', 'Curl de muñeca con mancuerna'),
  ('Caminhada do fazendeiro', 'en', 'Farmer''s Walk'),
  ('Caminhada do fazendeiro', 'es', 'Paseo del granjero'),
  ('Rolo de punho', 'en', 'Wrist Roller'),
  ('Rolo de punho', 'es', 'Rodillo de muñeca')
) as v(nome_pt, idioma, nome)
join public.exercicio e on e.nome = v.nome_pt
on conflict (exercicio_id, idioma) do nothing;
